/** Korean dictionaries per namespace: { "<namespace>": { "<key>": "<Korean text>" } }. */
const dictionaries = {
  "approval": {
    "allowOnce": "이번만 허용",
    "detail.aria": "승인 세부 정보",
    "escalation": "{toolName} 도구가 권한 상승 실행을 요청합니다",
    "reject": "거부",
    "waiting": "승인 대기 중"
  },
  "chat": {
    "chat.deepDiving": "깊이 탐색 중",
    "chat.deepDivingFor": "{duration}째 깊이 탐색 중 ···",
    "chat.loadError": "기록을 불러오지 못했습니다: {message} ({code})",
    "chat.loadOlder": "이전 기록 불러오기",
    "chat.loadingHistory": "기록 불러오는 중…",
    "chat.toBottom": "맨 아래로",
    "chat.turnNavigation.jump": "{turn}번째 턴으로 이동",
    "chat.turnNavigation.jumpLoad": "불러온 뒤 {turn}번째 턴으로 이동",
    "chat.turnNavigation.label": "턴 탐색",
    "chat.turnNavigation.turn": "턴 {turn}",
    "clock.md": "{m}/{d}",
    "clock.ymd": "{y}-{m}-{d}",
    "command.done": "완료",
    "command.failed": "명령 실패",
    "command.running": "실행 중…",
    "command.title": "명령",
    "duration.compactMinutes": "{minutes}분 {seconds}초",
    "duration.compactSeconds": "{seconds}초",
    "duration.hourUnit": "시간 ",
    "duration.milliseconds": "{milliseconds}ms",
    "duration.minuteUnit": "분 ",
    "duration.secondUnit": "초",
    "fileOpen.title": "파일을 열 수 없음",
    "fileOpen.unknown": "이 파일을 열 수 없습니다",
    "image.close": "이미지 미리보기 닫기",
    "image.dialog": "이미지 미리보기",
    "image.failed": "이미지 미리보기를 쓸 수 없음",
    "image.loading": "이미지 불러오는 중…",
    "image.open": "원본 크기로 보기",
    "json.truncated": "… 잘림, 전체 {total}자",
    "message.accountStopped": "작업 중지됨",
    "message.branch": "새 대화로 분기",
    "message.branchUnavailable": "완료된 턴의 마지막 메시지에서만 쓸 수 있습니다",
    "message.compaction": "컨텍스트 압축됨",
    "message.compaction.commandTitle": "compact",
    "message.compaction.completed": "기록 항목 {items}개를 압축함(약 {tokens}토큰)",
    "message.compaction.expand": "압축 요약 보기",
    "message.compaction.running": "컨텍스트 압축 중…",
    "message.compaction.unavailable": "압축 요약을 볼 수 없음",
    "message.context.catalog.more": "… {count}개 더 있음",
    "message.context.catalog.replaced": "교체된 목록",
    "message.context.instructions.added": "추가됨",
    "message.context.instructions.loaded": "불러옴",
    "message.context.instructions.removed": "제거됨",
    "message.context.instructions.updated": "업데이트됨",
    "message.context.recall.counts": "{retained}개 유지 · {omitted}개 생략",
    "message.context.recall.truncated": "잘림",
    "message.context.relay.from": "세션 {session}에서 전달",
    "message.context.snapshot.supersedes": "이전 스냅숏을 대체함",
    "message.contextInjection": "컨텍스트 주입",
    "message.contextRecall": "세션 기록 불러옴",
    "message.extraBlock": "추가 콘텐츠 블록",
    "message.failure.accountSignInRequired": "DeepSeek에 로그인한 뒤 요청을 받는 곳이 계정 인증을 지원하는지 확인해 주세요.",
    "message.failure.accountSignedOut": "DeepSeek에서 로그아웃해 중지되었습니다.",
    "message.failure.auth": "API 키가 올바르지 않습니다",
    "message.failure.quota": "요청 한도를 모두 썼습니다.",
    "message.maxTokens": "출력 토큰 한도에 도달함",
    "message.maxTokens.hint": "응답이 중간에 끊겼습니다. 앞선 출력은 대화에 남아 있습니다. \"계속\"이라고 보내면 모델이 이어서 답합니다.",
    "message.referenceSeparator": ", ",
    "message.referenceSummary": "참조한 세션 · {labels}",
    "message.retry.active": "모델 요청 다시 시도 중",
    "message.retry.cancelled": "모델 요청 재시도 취소됨",
    "message.retry.delay": "재시도 대기 시간: ",
    "message.retry.failure": "실패 원인: ",
    "message.retry.scheduled": "모델 요청 재시도 대기 중",
    "message.retry.started": "모델 요청을 다시 시도함",
    "message.retry.status": "{label} ({retry}/{maximum}) · {seconds}초",
    "message.stepProcess.code": "코드 실행 중",
    "message.stepProcess.comma": ", ",
    "message.stepProcess.commands": "명령 실행 중",
    "message.stepProcess.done.code": "코드 실행함",
    "message.stepProcess.done.commands": "명령 실행함",
    "message.stepProcess.done.edit": "파일 수정함",
    "message.stepProcess.done.plan": "계획 업데이트함",
    "message.stepProcess.done.questions": "질문함",
    "message.stepProcess.done.read": "파일 읽음",
    "message.stepProcess.done.readImage": "이미지 읽음",
    "message.stepProcess.done.search": "코드 검색함",
    "message.stepProcess.done.subagents": "서브에이전트 조율함",
    "message.stepProcess.done.thinking": "분석 완료",
    "message.stepProcess.done.tools": "도구 호출함",
    "message.stepProcess.done.webFetch": "웹 페이지 방문함",
    "message.stepProcess.done.webSearch": "웹 검색함",
    "message.stepProcess.done.write": "파일 작성함",
    "message.stepProcess.edit": "파일 수정 중",
    "message.stepProcess.joinTwo": "{first}, {second}",
    "message.stepProcess.more": "{title} 등",
    "message.stepProcess.plan": "계획 업데이트 중",
    "message.stepProcess.prepare.code": "코드 실행 준비 중",
    "message.stepProcess.prepare.commands": "명령 실행 준비 중",
    "message.stepProcess.prepare.edit": "파일 수정 준비 중",
    "message.stepProcess.prepare.plan": "계획 업데이트 준비 중",
    "message.stepProcess.prepare.questions": "질문 준비 중",
    "message.stepProcess.prepare.read": "파일 읽기 준비 중",
    "message.stepProcess.prepare.readImage": "이미지 읽기 준비 중",
    "message.stepProcess.prepare.search": "코드 검색 준비 중",
    "message.stepProcess.prepare.subagents": "서브에이전트 조율 준비 중",
    "message.stepProcess.prepare.tools": "도구 호출 준비 중",
    "message.stepProcess.prepare.webFetch": "웹 페이지 방문 준비 중",
    "message.stepProcess.prepare.webSearch": "웹 검색 준비 중",
    "message.stepProcess.prepare.write": "파일 작성 준비 중",
    "message.stepProcess.questions": "응답 기다리는 중",
    "message.stepProcess.read": "파일 읽는 중",
    "message.stepProcess.readImage": "이미지 읽는 중",
    "message.stepProcess.search": "코드 검색 중",
    "message.stepProcess.sharedPrefix": "",
    "message.stepProcess.subagents": "서브에이전트 조율 중",
    "message.stepProcess.thinking": "요청 분석 중",
    "message.stepProcess.tools": "도구 호출 중",
    "message.stepProcess.webFetch": "웹 페이지 방문 중",
    "message.stepProcess.webSearch": "웹 검색 중",
    "message.stepProcess.write": "파일 작성 중",
    "message.stopped": "중지됨",
    "message.systemPrompt": "시스템 프롬프트",
    "message.systemPromptUpdate": "시스템 프롬프트 업데이트",
    "message.think": "생각",
    "message.tokensPerSecond": "{tps} tok/s",
    "message.toolAdded": "도구 추가됨: {name}",
    "message.toolRemoved": "도구 제거됨: {name}",
    "message.toolsAdded": "추가됨: {names}",
    "message.toolsAddedCount": "{count}개 추가됨",
    "message.toolsChanged": "{added}개 추가, {removed}개 제거",
    "message.toolsRemoved": "제거됨: {names}",
    "message.toolsRemovedCount": "{count}개 제거됨",
    "message.toolsUpdated": "도구 업데이트됨",
    "message.trigger.agent": "작업 메시지 받음",
    "message.trigger.explanation": "이 알림을 받고 응답을 시작했습니다.",
    "message.trigger.github": "GitHub 이벤트 받음",
    "message.trigger.goal": "목표 이어서 진행",
    "message.trigger.job": "백그라운드 작업 업데이트됨",
    "message.trigger.plugin": "플러그인 상태 업데이트됨",
    "message.trigger.request": "실행 요청됨",
    "message.trigger.schedule": "자동화 작업",
    "message.trigger.subagent": "하위 작업 상태 업데이트됨",
    "message.trigger.team": "팀 메시지 받음",
    "message.trigger.webhook": "외부 이벤트 받음",
    "message.turnError": "이 턴이 실패했습니다",
    "message.turnProcess.failed": "실패",
    "message.turnProcess.messages.one": "메시지 {count}개",
    "message.turnProcess.messages.other": "메시지 {count}개",
    "message.turnProcess.separator": " · ",
    "message.turnProcess.subagents.one": "서브에이전트 {count}개",
    "message.turnProcess.subagents.other": "서브에이전트 {count}개",
    "message.turnProcess.thoughtForAWhile": "잠시 생각함",
    "message.turnProcess.took": "소요 시간 ",
    "message.turnProcess.toolCalls.one": "도구 호출 {count}회",
    "message.turnProcess.toolCalls.other": "도구 호출 {count}회",
    "message.turnProcess.worked": "완료",
    "message.turnUsage.cacheHit": "캐시 적중",
    "message.turnUsage.cacheRead": "캐시된 입력",
    "message.turnUsage.cacheWrite": "캐시 쓰기",
    "message.turnUsage.consumed": "사용량 {total}",
    "message.turnUsage.count": "{count} tok",
    "message.turnUsage.input": "캐시되지 않은 입력",
    "message.turnUsage.model": "공급자 / 모델",
    "message.turnUsage.output": "출력",
    "message.turnUsage.reasoning": " (추론 {tokens})",
    "message.turnUsage.title": "턴 사용량",
    "message.unknownBlock": "알 수 없는 콘텐츠 블록",
    "message.unknownSurface": "알 수 없는 화면 이벤트: {type}",
    "number.groupSeparator": ",",
    "row.failed": "실패",
    "row.running": "실행 중",
    "settings.links.description": "웹 링크를 어디서 열지 고릅니다",
    "settings.links.newTab": "기본 브라우저",
    "settings.links.sidebar": "앱 안 사이드바",
    "settings.links.title": "채팅 링크 열기 위치",
    "settings.performance.compact": "간단히",
    "settings.performance.description": "성능과 사용량 정보를 얼마나 보여 줄지 고릅니다",
    "settings.performance.detailed": "자세히",
    "settings.performance.title": "성능 및 사용량",
    "settings.transcript.compact": "간단히",
    "settings.transcript.description": "도구 호출을 얼마나 자세히 보여 줄지 고릅니다",
    "settings.transcript.detailed": "자세히",
    "settings.transcript.standard": "보통",
    "settings.transcript.title": "작업 과정 표시",
    "settings.transcript.verbose": "모두 표시",
    "stats.cacheHit": "캐시 적중 {percent}%",
    "stats.counts": "턴 {turns}개, 단계 {steps}개",
    "stats.dialog.llmTime": "LLM 시간",
    "stats.dialog.speed": "초당 토큰 수(TPS)",
    "stats.dialog.title": "세션 통계",
    "stats.dialog.toolTime": "도구 시간",
    "stats.dialog.ttft": "첫 토큰까지 평균 시간(TTFT)",
    "stats.dialog.usageTitle": "토큰 사용량",
    "view.chat": "채팅"
  },
  "command": {
    "description.compact": "오래된 대화 기록 압축",
    "description.export": "이 세션 로그를 ZIP 파일로 내려받기",
    "description.feedback": "이 세션에 대한 피드백 남기기",
    "description.goal": "오래 걸리는 작업의 목표 설정 또는 보기",
    "description.permission": "권한 프리셋 전환(샌드박스 모드 + 승인 정책)",
    "description.plan": "계획 모드 시작 또는 종료",
    "label.compact": "압축",
    "label.export": "내보내기",
    "label.feedback": "피드백",
    "label.goal": "목표",
    "label.permission": "권한",
    "label.plan": "계획",
    "listbox.aria": "/{command} 검색 결과",
    "notice.attachmentsUnsupported": "/{command} 명령에는 첨부 파일을 쓸 수 없습니다. 먼저 첨부 파일을 빼 주세요",
    "overlay.aria": "/{command} 옵션",
    "search.aria": "옵션 필터",
    "search.placeholder": "검색…",
    "section.add": "추가",
    "section.commands": "명령",
    "status.applying": "적용하는 중…",
    "status.empty": "옵션 없음",
    "status.loading": "옵션 불러오는 중…",
    "token.compact": "compact",
    "token.export": "export",
    "token.feedback": "feedback",
    "token.goal": "goal",
    "token.permission": "permission",
    "token.plan": "plan"
  },
  "common": {
    "back": "뒤로",
    "brand.localBuild": "DSH 로컬 빌드",
    "cancel": "취소",
    "close": "닫기",
    "codeBlock.title": "코드 블록",
    "codeBlock.unwrap": "줄 바꿈 안 함",
    "codeBlock.wrap": "줄 바꿈",
    "collapse": "접기",
    "copied": "복사됨",
    "copy": "복사",
    "copy.compactJson": "한 줄 JSON 복사",
    "copy.failed": "복사 실패",
    "copy.json": "JSON 복사",
    "copy.optionsHint": "{action}, 오른쪽 클릭하면 복사 옵션",
    "copy.path": "속성 경로 복사",
    "copy.prettyJson": "정렬된 JSON 복사",
    "copy.value": "값 복사",
    "delete": "삭제",
    "edit": "편집",
    "expand": "펼치기",
    "json.label": "JSON",
    "load.failed": "불러오지 못함",
    "loading": "불러오는 중…",
    "markdown.footnotes": "각주",
    "markdown.truncatedCharacters": "… {total}자에서 잘림",
    "more": "더 보기",
    "next": "다음",
    "none": "없음",
    "number.million": "{value}M",
    "number.thousand": "{value}K",
    "ok": "확인",
    "previous": "이전",
    "retry": "다시 시도",
    "save": "저장",
    "search": "검색",
    "skip": "건너뛰기",
    "submit": "제출",
    "submitting": "제출하는 중…",
    "truncated": "잘림",
    "unknown": "알 수 없음",
    "workspace.defaultName": "기본 워크스페이스"
  },
  "trajectory": {
    "attachment.imageName": "이미지 {index}",
    "attachment.list": "첨부 파일",
    "block.label": "블록 #{index} {type}",
    "block.openSummary": "블록 #{index} 도구 호출 요약 열기",
    "block.openSummaryTitle": "도구 호출 요약 열기",
    "code.copyOutput": "출력 복사",
    "code.copySource": "코드 복사",
    "code.originalJson": "원본 JSON",
    "code.output": "출력",
    "code.running": "실행 중…",
    "code.source": "코드",
    "column.input": "입력",
    "column.model": "모델",
    "column.output": "출력",
    "column.think": "생각",
    "column.time": "시간",
    "column.tools": "도구",
    "details.assistantMessage": "어시스턴트 메시지",
    "details.close": "세부 정보 닫기",
    "details.compacted": "압축됨",
    "details.error": "오류",
    "details.event": "이벤트 세부 정보",
    "details.failure.auth": "API 키가 올바르지 않습니다",
    "details.hierarchy": "계층",
    "details.model": "모델",
    "details.provider": "공급자",
    "details.purpose": "용도",
    "details.resize": "이벤트 세부 정보 크기 조절",
    "details.resizeTitle": "끌어서 크기를 조절합니다. 두 번 클릭하면 원래대로 돌아갑니다.",
    "details.result": "결과",
    "details.retry": "재시도",
    "details.retryDelay": "재시도 대기 시간",
    "details.scheduled": "예약됨",
    "details.source": "출처",
    "details.status": "상태",
    "details.subtoolCalls": "하위 도구 호출",
    "details.toolCall": "도구 호출",
    "details.toolCalls": "도구 호출",
    "group.compaction": "압축 {seq}",
    "group.message": "메시지",
    "group.step": "단계 {step}",
    "history.clickToLoadEarlier": "클릭해 이전 기록 불러오기",
    "history.loadEarlier": "이전 기록 불러오기",
    "history.loadingEarlier": "이전 기록 불러오는 중…",
    "history.loadingEarlierAria": "이전 기록 불러오는 중…",
    "history.loadingTrajectory": "실행 기록 불러오는 중…",
    "kind.assistant": "어시스턴트",
    "kind.compacted": "압축됨",
    "kind.context": "컨텍스트",
    "kind.message": "메시지",
    "kind.sub": "하위",
    "kind.subtool": "하위 도구",
    "kind.system": "시스템",
    "kind.tool": "도구",
    "kind.user": "사용자",
    "layout.compacted": "컨텍스트 압축됨",
    "layout.compacting": "컨텍스트 압축 중…",
    "layout.compactionFailed": "압축 실패",
    "layout.compactionInterrupted": "압축이 끝나기 전에 중단되었습니다.",
    "layout.fileAttachments": "파일 ×{count}",
    "layout.imageCount": "이미지 ×{count}",
    "layout.initialSystemPrompt": "초기 시스템 프롬프트",
    "layout.systemPromptAndToolsUpdated": "시스템 프롬프트와 도구 업데이트됨",
    "layout.systemPromptUpdated": "시스템 프롬프트 업데이트됨",
    "layout.toolAdded": "도구 추가됨: {name}",
    "layout.toolCallOnly": "도구 호출만",
    "layout.toolRemoved": "도구 제거됨: {name}",
    "layout.toolUpdateNotice": "도구 업데이트됨",
    "layout.toolsAdded": "추가됨: {names}",
    "layout.toolsAddedCount": "{count}개 추가됨",
    "layout.toolsChanged": "{added}개 추가, {removed}개 제거",
    "layout.toolsRemoved": "제거됨: {names}",
    "layout.toolsRemovedCount": "{count}개 제거됨",
    "layout.toolsUpdated": "도구 업데이트됨",
    "options.json": "요청 옵션 JSON",
    "options.notRecorded": "옵션이 기록되지 않음",
    "record.json": "JSON",
    "record.namedParametersJson": "{name} 매개변수 JSON",
    "record.noContent": "내용 없음",
    "record.noOutput": "출력 없음",
    "record.noPayload": "기록된 페이로드 없음",
    "record.noResult": "기록된 결과 없음",
    "record.outputJson": "결과 JSON",
    "record.parameters": "매개변수",
    "record.parametersJson": "매개변수 JSON",
    "record.payloadJson": "페이로드 JSON",
    "record.resultJson": "결과 JSON",
    "record.schemaUnavailable": "스키마 없음",
    "record.systemPrompt": "시스템 프롬프트",
    "record.systemPromptMissing": "이 요청에는 시스템 프롬프트가 없습니다",
    "record.thinking": "생각",
    "record.toolCallOnly": "(도구 호출만)",
    "record.tools": "도구",
    "record.toolsMissing": "이 요청에는 도구가 없습니다",
    "record.wrapLines": "줄 바꿈",
    "request.collapsedAssistant": "어시스턴트",
    "request.collapsedSummary": "접힌 {kind} 요약, {summary}",
    "request.collapsedTurn": "턴",
    "request.compaction": "압축 · {section}",
    "request.compactionPurpose": "압축",
    "request.label": "요청 #{request}",
    "request.labelCompaction": "요청 #{request} · 압축",
    "request.noContent": "내용 없음",
    "request.retryProgress": "{retry}/{maximum}",
    "request.rowAria": "{request}{kind}, {content}",
    "request.rowAriaCompaction": "요청 {request}, 압축",
    "request.rowPrefix": "요청 {request}, ",
    "section.betweenTurns": "턴 사이",
    "source.goal": "목표",
    "source.goalRound": "목표 · {round}회차",
    "source.messageJson": "메시지 원본 JSON",
    "source.notRecorded": "출처가 기록되지 않음",
    "source.plugin": "플러그인",
    "source.pluginNamed": "플러그인 · {plugin}",
    "source.unknown": "알 수 없음",
    "source.user": "사용자",
    "status.completed": "완료",
    "status.failed": "실패",
    "status.pending": "대기 중",
    "summary.steps.one": "단계 {count}개",
    "summary.steps.other": "단계 {count}개",
    "summary.toolCalls.one": "도구 호출 {count}회",
    "summary.toolCalls.other": "도구 호출 {count}회",
    "tab.diff": "변경 사항",
    "tab.options": "옵션",
    "tab.payload": "페이로드",
    "tab.preview": "미리보기",
    "tab.raw": "원본",
    "tab.rawOutput": "원본 출력",
    "tab.result": "결과",
    "tab.schema": "스키마",
    "tab.source": "출처",
    "tab.summary": "요약",
    "tab.systemPrompt": "시스템 프롬프트",
    "tab.timing": "시간",
    "tab.tools": "도구",
    "tab.usage": "사용량",
    "timeline.aria": "실행 기록 타임라인",
    "timeline.noTimingData": "시간 데이터 없음",
    "timeline.overviewAria": "타임라인 개요, 가로로 끌어서 이벤트 구간을 확대합니다",
    "timeline.started": "시작 {time}",
    "timeline.total": "합계 {duration}",
    "timeline.ttftDecoding": "TTFT {ttft} · 디코딩 {decoding}",
    "timing.duration": "소요 시간",
    "timing.durationTooShort": "소요 시간이 너무 짧음",
    "timing.firstTokenUnavailable": "첫 토큰 정보 없음",
    "timing.generation": "생성",
    "timing.notAvailable": "정보 없음",
    "timing.notRecorded": "기록되지 않음",
    "timing.outputTokensUnavailable": "출력 토큰 정보 없음",
    "timing.request": "요청 시간",
    "timing.sessionTimestamps": "세션 타임스탬프",
    "timing.sessionTimestampsRunning": "세션 타임스탬프(실행 중)",
    "timing.showLocalTime": "현지 시각 표시",
    "timing.showUnixTimestamp": "Unix 타임스탬프 표시",
    "timing.source": "시간 출처",
    "timing.started": "시작",
    "timing.stepStartUnavailable": "단계 시작 정보 없음",
    "timing.throughput": "처리량",
    "timing.totalDuration": "전체 소요 시간",
    "timing.ttft": "TTFT",
    "timing.usageUnavailable": "사용량 정보 없음",
    "toolbar.actualTime": "실제 시간",
    "toolbar.aria": "실행 기록 도구 모음",
    "toolbar.calls": "호출",
    "toolbar.collapseCalls": "호출 접기",
    "toolbar.collapseTurns": "턴 접기",
    "toolbar.duration": "소요 시간",
    "toolbar.expandCalls": "호출 펼치기",
    "toolbar.expandTurns": "턴 펼치기",
    "toolbar.search": "실행 기록 검색",
    "toolbar.searchPlaceholder": "검색",
    "toolbar.turns": "턴",
    "toolbar.useActualDuration": "실제 소요 시간으로 표시",
    "toolbar.useEqualWidth": "작업을 같은 너비로 표시",
    "turn.label": "턴 {turn}",
    "unit.milliseconds": "{value} ms",
    "unit.seconds": "{value}초",
    "unit.tokens": "{value} tok",
    "unit.tokensPerSecond": "{value} tok/s",
    "usage.cacheCreated": "캐시 생성",
    "usage.cached": "캐시됨",
    "usage.content": "콘텐츠",
    "usage.input": "입력",
    "usage.notReported": "사용량이 보고되지 않음",
    "usage.other": "기타",
    "usage.output": "출력",
    "usage.reasoning": "추론",
    "usage.sessionCumulative": "세션 누적",
    "usage.thisRequest": "이번 요청",
    "usage.tokens": "토큰",
    "view.trajectory": "실행 기록"
  }
}

window.__ModuleLoader__.load({
  id: 'dsh-locale-ko',
  factory: () => ({
    inject: ['locale'],
    apply(ctx) {
      ctx.effect(() => ctx.locale.addLanguage({ id: 'ko', label: '한국어', fallback: 'en' }), 'dsh-locale-ko: language')
      for (const [ns, dict] of Object.entries(dictionaries)) {
        ctx.effect(() => ctx.locale.register(ns, 'ko', dict), `dsh-locale-ko: ${ns}`)
      }
    },
  }),
})
