/** Korean dictionaries per namespace: { "<namespace>": { "<key>": "<Korean text>" } }. */
const dictionaries = {
  "approval": {
    "allowOnce": "이번만 허용",
    "detail.aria": "승인 세부 정보",
    "escalation": "{toolName} 도구가 권한 상승 실행을 요청합니다",
    "reject": "거부",
    "waiting": "승인 대기 중"
  },
  "chat": {
    "chat.deepDiving": "깊이 탐색 중",
    "chat.deepDivingFor": "{duration}째 깊이 탐색 중 ···",
    "chat.loadError": "기록을 불러오지 못했습니다: {message} ({code})",
    "chat.loadOlder": "이전 기록 불러오기",
    "chat.loadingHistory": "기록 불러오는 중…",
    "chat.toBottom": "맨 아래로",
    "chat.turnNavigation.jump": "{turn}번째 턴으로 이동",
    "chat.turnNavigation.jumpLoad": "불러온 뒤 {turn}번째 턴으로 이동",
    "chat.turnNavigation.label": "턴 탐색",
    "chat.turnNavigation.turn": "턴 {turn}",
    "clock.md": "{m}/{d}",
    "clock.ymd": "{y}-{m}-{d}",
    "command.done": "완료",
    "command.failed": "명령 실패",
    "command.running": "실행 중…",
    "command.title": "명령",
    "duration.compactMinutes": "{minutes}분 {seconds}초",
    "duration.compactSeconds": "{seconds}초",
    "duration.hourUnit": "시간 ",
    "duration.milliseconds": "{milliseconds}ms",
    "duration.minuteUnit": "분 ",
    "duration.secondUnit": "초",
    "fileOpen.title": "파일을 열 수 없음",
    "fileOpen.unknown": "이 파일을 열 수 없습니다",
    "image.close": "이미지 미리보기 닫기",
    "image.dialog": "이미지 미리보기",
    "image.failed": "이미지 미리보기를 쓸 수 없음",
    "image.loading": "이미지 불러오는 중…",
    "image.open": "원본 크기로 보기",
    "json.truncated": "… 잘림, 전체 {total}자",
    "message.accountStopped": "작업 중지됨",
    "message.branch": "새 대화로 분기",
    "message.branchUnavailable": "완료된 턴의 마지막 메시지에서만 쓸 수 있습니다",
    "message.compaction": "컨텍스트 압축됨",
    "message.compaction.commandTitle": "compact",
    "message.compaction.completed": "기록 항목 {items}개를 압축함(약 {tokens}토큰)",
    "message.compaction.expand": "압축 요약 보기",
    "message.compaction.running": "컨텍스트 압축 중…",
    "message.compaction.unavailable": "압축 요약을 볼 수 없음",
    "message.context.catalog.more": "… {count}개 더 있음",
    "message.context.catalog.replaced": "교체된 목록",
    "message.context.instructions.added": "추가됨",
    "message.context.instructions.loaded": "불러옴",
    "message.context.instructions.removed": "제거됨",
    "message.context.instructions.updated": "업데이트됨",
    "message.context.recall.counts": "{retained}개 유지 · {omitted}개 생략",
    "message.context.recall.truncated": "잘림",
    "message.context.relay.from": "세션 {session}에서 전달",
    "message.context.snapshot.supersedes": "이전 스냅숏을 대체함",
    "message.contextInjection": "컨텍스트 주입",
    "message.contextRecall": "세션 기록 불러옴",
    "message.extraBlock": "추가 콘텐츠 블록",
    "message.failure.accountSignInRequired": "DeepSeek에 로그인한 뒤 요청을 받는 곳이 계정 인증을 지원하는지 확인해 주세요.",
    "message.failure.accountSignedOut": "DeepSeek에서 로그아웃해 중지되었습니다.",
    "message.failure.auth": "API 키가 올바르지 않습니다",
    "message.failure.quota": "요청 한도를 모두 썼습니다.",
    "message.maxTokens": "출력 토큰 한도에 도달함",
    "message.maxTokens.hint": "응답이 중간에 끊겼습니다. 앞선 출력은 대화에 남아 있습니다. \"계속\"이라고 보내면 모델이 이어서 답합니다.",
    "message.referenceSeparator": ", ",
    "message.referenceSummary": "참조한 세션 · {labels}",
    "message.retry.active": "모델 요청 다시 시도 중",
    "message.retry.cancelled": "모델 요청 재시도 취소됨",
    "message.retry.delay": "재시도 대기 시간: ",
    "message.retry.failure": "실패 원인: ",
    "message.retry.scheduled": "모델 요청 재시도 대기 중",
    "message.retry.started": "모델 요청을 다시 시도함",
    "message.retry.status": "{label} ({retry}/{maximum}) · {seconds}초",
    "message.stepProcess.code": "코드 실행 중",
    "message.stepProcess.comma": ", ",
    "message.stepProcess.commands": "명령 실행 중",
    "message.stepProcess.done.code": "코드 실행함",
    "message.stepProcess.done.commands": "명령 실행함",
    "message.stepProcess.done.edit": "파일 수정함",
    "message.stepProcess.done.plan": "계획 업데이트함",
    "message.stepProcess.done.questions": "질문함",
    "message.stepProcess.done.read": "파일 읽음",
    "message.stepProcess.done.readImage": "이미지 읽음",
    "message.stepProcess.done.search": "코드 검색함",
    "message.stepProcess.done.subagents": "서브에이전트 조율함",
    "message.stepProcess.done.thinking": "분석 완료",
    "message.stepProcess.done.tools": "도구 호출함",
    "message.stepProcess.done.webFetch": "웹 페이지 방문함",
    "message.stepProcess.done.webSearch": "웹 검색함",
    "message.stepProcess.done.write": "파일 작성함",
    "message.stepProcess.edit": "파일 수정 중",
    "message.stepProcess.joinTwo": "{first}, {second}",
    "message.stepProcess.more": "{title} 등",
    "message.stepProcess.plan": "계획 업데이트 중",
    "message.stepProcess.prepare.code": "코드 실행 준비 중",
    "message.stepProcess.prepare.commands": "명령 실행 준비 중",
    "message.stepProcess.prepare.edit": "파일 수정 준비 중",
    "message.stepProcess.prepare.plan": "계획 업데이트 준비 중",
    "message.stepProcess.prepare.questions": "질문 준비 중",
    "message.stepProcess.prepare.read": "파일 읽기 준비 중",
    "message.stepProcess.prepare.readImage": "이미지 읽기 준비 중",
    "message.stepProcess.prepare.search": "코드 검색 준비 중",
    "message.stepProcess.prepare.subagents": "서브에이전트 조율 준비 중",
    "message.stepProcess.prepare.tools": "도구 호출 준비 중",
    "message.stepProcess.prepare.webFetch": "웹 페이지 방문 준비 중",
    "message.stepProcess.prepare.webSearch": "웹 검색 준비 중",
    "message.stepProcess.prepare.write": "파일 작성 준비 중",
    "message.stepProcess.questions": "응답 기다리는 중",
    "message.stepProcess.read": "파일 읽는 중",
    "message.stepProcess.readImage": "이미지 읽는 중",
    "message.stepProcess.search": "코드 검색 중",
    "message.stepProcess.sharedPrefix": "",
    "message.stepProcess.subagents": "서브에이전트 조율 중",
    "message.stepProcess.thinking": "요청 분석 중",
    "message.stepProcess.tools": "도구 호출 중",
    "message.stepProcess.webFetch": "웹 페이지 방문 중",
    "message.stepProcess.webSearch": "웹 검색 중",
    "message.stepProcess.write": "파일 작성 중",
    "message.stopped": "중지됨",
    "message.systemPrompt": "시스템 프롬프트",
    "message.systemPromptUpdate": "시스템 프롬프트 업데이트",
    "message.think": "생각",
    "message.tokensPerSecond": "{tps} tok/s",
    "message.toolAdded": "도구 추가됨: {name}",
    "message.toolRemoved": "도구 제거됨: {name}",
    "message.toolsAdded": "추가됨: {names}",
    "message.toolsAddedCount": "{count}개 추가됨",
    "message.toolsChanged": "{added}개 추가, {removed}개 제거",
    "message.toolsRemoved": "제거됨: {names}",
    "message.toolsRemovedCount": "{count}개 제거됨",
    "message.toolsUpdated": "도구 업데이트됨",
    "message.trigger.agent": "작업 메시지 받음",
    "message.trigger.explanation": "이 알림을 받고 응답을 시작했습니다.",
    "message.trigger.github": "GitHub 이벤트 받음",
    "message.trigger.goal": "목표 이어서 진행",
    "message.trigger.job": "백그라운드 작업 업데이트됨",
    "message.trigger.plugin": "플러그인 상태 업데이트됨",
    "message.trigger.request": "실행 요청됨",
    "message.trigger.schedule": "자동화 작업",
    "message.trigger.subagent": "하위 작업 상태 업데이트됨",
    "message.trigger.team": "팀 메시지 받음",
    "message.trigger.webhook": "외부 이벤트 받음",
    "message.turnError": "이 턴이 실패했습니다",
    "message.turnProcess.failed": "실패",
    "message.turnProcess.messages.one": "메시지 {count}개",
    "message.turnProcess.messages.other": "메시지 {count}개",
    "message.turnProcess.separator": " · ",
    "message.turnProcess.subagents.one": "서브에이전트 {count}개",
    "message.turnProcess.subagents.other": "서브에이전트 {count}개",
    "message.turnProcess.thoughtForAWhile": "잠시 생각함",
    "message.turnProcess.took": "소요 시간 ",
    "message.turnProcess.toolCalls.one": "도구 호출 {count}회",
    "message.turnProcess.toolCalls.other": "도구 호출 {count}회",
    "message.turnProcess.worked": "완료",
    "message.turnUsage.cacheHit": "캐시 적중",
    "message.turnUsage.cacheRead": "캐시된 입력",
    "message.turnUsage.cacheWrite": "캐시 쓰기",
    "message.turnUsage.consumed": "사용량 {total}",
    "message.turnUsage.count": "{count} tok",
    "message.turnUsage.input": "캐시되지 않은 입력",
    "message.turnUsage.model": "공급자 / 모델",
    "message.turnUsage.output": "출력",
    "message.turnUsage.reasoning": " (추론 {tokens})",
    "message.turnUsage.title": "턴 사용량",
    "message.unknownBlock": "알 수 없는 콘텐츠 블록",
    "message.unknownSurface": "알 수 없는 화면 이벤트: {type}",
    "number.groupSeparator": ",",
    "row.failed": "실패",
    "row.running": "실행 중",
    "settings.links.description": "웹 링크를 어디서 열지 고릅니다",
    "settings.links.newTab": "기본 브라우저",
    "settings.links.sidebar": "앱 안 사이드바",
    "settings.links.title": "채팅 링크 열기 위치",
    "settings.performance.compact": "간단히",
    "settings.performance.description": "성능과 사용량 정보를 얼마나 보여 줄지 고릅니다",
    "settings.performance.detailed": "자세히",
    "settings.performance.title": "성능 및 사용량",
    "settings.transcript.compact": "간단히",
    "settings.transcript.description": "도구 호출을 얼마나 자세히 보여 줄지 고릅니다",
    "settings.transcript.detailed": "자세히",
    "settings.transcript.standard": "보통",
    "settings.transcript.title": "작업 과정 표시",
    "settings.transcript.verbose": "모두 표시",
    "stats.cacheHit": "캐시 적중 {percent}%",
    "stats.counts": "턴 {turns}개, 단계 {steps}개",
    "stats.dialog.llmTime": "LLM 시간",
    "stats.dialog.speed": "초당 토큰 수(TPS)",
    "stats.dialog.title": "세션 통계",
    "stats.dialog.toolTime": "도구 시간",
    "stats.dialog.ttft": "첫 토큰까지 평균 시간(TTFT)",
    "stats.dialog.usageTitle": "토큰 사용량",
    "view.chat": "채팅"
  },
  "command": {
    "description.compact": "오래된 대화 기록 압축",
    "description.export": "이 세션 로그를 ZIP 파일로 내려받기",
    "description.feedback": "이 세션에 대한 피드백 남기기",
    "description.goal": "오래 걸리는 작업의 목표 설정 또는 보기",
    "description.permission": "권한 프리셋 전환(샌드박스 모드 + 승인 정책)",
    "description.plan": "계획 모드 시작 또는 종료",
    "label.compact": "압축",
    "label.export": "내보내기",
    "label.feedback": "피드백",
    "label.goal": "목표",
    "label.permission": "권한",
    "label.plan": "계획",
    "listbox.aria": "/{command} 검색 결과",
    "notice.attachmentsUnsupported": "/{command} 명령에는 첨부 파일을 쓸 수 없습니다. 먼저 첨부 파일을 빼 주세요",
    "overlay.aria": "/{command} 옵션",
    "search.aria": "옵션 필터",
    "search.placeholder": "검색…",
    "section.add": "추가",
    "section.commands": "명령",
    "status.applying": "적용하는 중…",
    "status.empty": "옵션 없음",
    "status.loading": "옵션 불러오는 중…",
    "token.compact": "compact",
    "token.export": "export",
    "token.feedback": "feedback",
    "token.goal": "goal",
    "token.permission": "permission",
    "token.plan": "plan"
  },
  "common": {
    "back": "뒤로",
    "brand.localBuild": "DSH 로컬 빌드",
    "cancel": "취소",
    "close": "닫기",
    "codeBlock.title": "코드 블록",
    "codeBlock.unwrap": "줄 바꿈 안 함",
    "codeBlock.wrap": "줄 바꿈",
    "collapse": "접기",
    "copied": "복사됨",
    "copy": "복사",
    "copy.compactJson": "한 줄 JSON 복사",
    "copy.failed": "복사 실패",
    "copy.json": "JSON 복사",
    "copy.optionsHint": "{action}, 오른쪽 클릭하면 복사 옵션",
    "copy.path": "속성 경로 복사",
    "copy.prettyJson": "정렬된 JSON 복사",
    "copy.value": "값 복사",
    "delete": "삭제",
    "edit": "편집",
    "expand": "펼치기",
    "json.label": "JSON",
    "load.failed": "불러오지 못함",
    "loading": "불러오는 중…",
    "markdown.footnotes": "각주",
    "markdown.truncatedCharacters": "… {total}자에서 잘림",
    "more": "더 보기",
    "next": "다음",
    "none": "없음",
    "number.million": "{value}M",
    "number.thousand": "{value}K",
    "ok": "확인",
    "previous": "이전",
    "retry": "다시 시도",
    "save": "저장",
    "search": "검색",
    "skip": "건너뛰기",
    "submit": "제출",
    "submitting": "제출하는 중…",
    "truncated": "잘림",
    "unknown": "알 수 없음",
    "workspace.defaultName": "기본 워크스페이스"
  },
  "conversation": {
    "ask.answered": "{answered}/{total} 답변함",
    "ask.cancelled": "취소됨",
    "ask.cancelledDetail": "답변을 제출하기 전에 질문이 취소되었습니다.",
    "ask.closed": "닫힘",
    "ask.closedDetail": "닫힌 질문입니다. 결과는 아래 대화에 있습니다.",
    "ask.interrupted": "중단됨",
    "ask.interruptedDetail": "답변을 제출하기 전에 질문이 중단되었습니다.",
    "ask.pending": "작업은 계속됨, 아직 답변 가능",
    "ask.pendingDetail": "대기 중인 질문에는 입력창에서 계속 답할 수 있습니다.",
    "ask.reopen": "답변하기",
    "ask.review": "답변 보기",
    "ask.rowTitle": "질문",
    "ask.skipped": "답변하지 않음",
    "ask.waiting": "대기 중",
    "attachment.directoryDesktopOnly": "폴더는 데스크톱 앱에서만 추가할 수 있습니다. 브라우저에서는 파일을 하나씩 추가해 주세요",
    "attachment.dropBlocked": "지금은 파일과 이미지를 추가할 수 없습니다",
    "attachment.dropDesc": "이미지는 최대 {count}개, 개당 {size}까지",
    "attachment.dropTitle": "파일이나 이미지를 여기로 끌어다 놓으세요",
    "attachment.pathUnavailable": "폴더 경로를 가져오지 못했습니다. 다시 끌어다 놓아 주세요",
    "attachment.pathUnsupported": "경로에 참조로 담을 수 없는 문자가 있습니다. 이름을 바꾼 뒤 다시 시도해 주세요",
    "attachment.pending": "대기 중인 첨부 파일",
    "attachment.scrollLeft": "첨부 파일 왼쪽으로 스크롤",
    "attachment.scrollRight": "첨부 파일 오른쪽으로 스크롤",
    "bash.failed": "실패",
    "bash.running": "실행 중",
    "bash.stopped": "중지됨",
    "command.attachmentsUnsupported": "/{command} 명령에는 첨부 파일을 쓸 수 없습니다. 먼저 첨부 파일을 빼 주세요",
    "context.aria": "컨텍스트 {percent} 사용됨",
    "context.messages": "메시지",
    "context.system": "시스템 프롬프트",
    "context.tools": "도구 정의",
    "context.used": "컨텍스트 사용량",
    "detail.agent.reply": "에이전트 응답",
    "detail.agents.count": "에이전트 {count}개",
    "detail.days": "{count}일",
    "detail.empty": "결과 없음",
    "detail.event.neighbors": "주변 이벤트",
    "detail.field.agent": "에이전트 ID",
    "detail.field.agents": "시작한 에이전트",
    "detail.field.availability": "사용 가능 여부",
    "detail.field.bestMatch": "가장 비슷한 항목",
    "detail.field.callId": "호출 ID",
    "detail.field.content": "내용",
    "detail.field.context": "컨텍스트",
    "detail.field.currentPackage": "현재 패키지",
    "detail.field.data": "데이터",
    "detail.field.dependencies": "의존성",
    "detail.field.depth": "깊이",
    "detail.field.diagnostics": "진단",
    "detail.field.exitCode": "종료 코드",
    "detail.field.id": "ID",
    "detail.field.inputSchema": "입력 스키마",
    "detail.field.job": "작업 ID",
    "detail.field.latestRun": "최근 실행",
    "detail.field.message": "메시지",
    "detail.field.messageId": "메시지 ID",
    "detail.field.methods": "메서드",
    "detail.field.model": "모델",
    "detail.field.nextPackage": "다음 패키지",
    "detail.field.outputSchema": "출력 스키마",
    "detail.field.owner": "소유자",
    "detail.field.packages": "패키지",
    "detail.field.parent": "상위",
    "detail.field.pid": "프로세스 ID",
    "detail.field.platform": "플랫폼",
    "detail.field.previousStatus": "이전 상태",
    "detail.field.processGroup": "프로세스 그룹",
    "detail.field.props": "속성",
    "detail.field.provider": "공급자",
    "detail.field.ready": "준비됨",
    "detail.field.registrations": "등록 항목",
    "detail.field.result": "결과",
    "detail.field.revision": "리비전",
    "detail.field.role": "역할",
    "detail.field.root": "루트",
    "detail.field.seq": "이벤트 순번",
    "detail.field.signal": "시그널",
    "detail.field.source": "출처",
    "detail.field.step": "단계",
    "detail.field.surface": "기록 상태",
    "detail.field.target": "대상 이벤트",
    "detail.field.task": "작업",
    "detail.field.time": "시간",
    "detail.field.turn": "턴",
    "detail.field.type": "유형",
    "detail.field.warnings": "경고",
    "detail.field.writeScopes": "쓰기 범위",
    "detail.goal.active": "진행 중",
    "detail.goal.blocked": "막힘",
    "detail.goal.complete": "완료",
    "detail.goal.disarmed": "계속 진행 대기 중",
    "detail.goal.empty": "목표 없음",
    "detail.goal.paused": "일시 중지됨",
    "detail.goal.reason": "막힌 이유",
    "detail.goal.rounds": "회차",
    "detail.hours": "{count}시간",
    "detail.jobs.count": "백그라운드 작업 {count}개",
    "detail.location": "{line}행 {column}열",
    "detail.locations.count": "위치 {count}곳",
    "detail.matches.capped": "결과 한도에 도달했습니다. 더 보려면 검색 범위를 좁혀 주세요",
    "detail.matches.count": "일치 항목 {count}개",
    "detail.minutes": "{count}분",
    "detail.models.title": "사용 가능한 모델",
    "detail.moreInInspect": "검사에서 항목 {count}개를 더 볼 수 있습니다",
    "detail.no": "아니요",
    "detail.none": "없음",
    "detail.output.lines": "전체 {total}줄 중 {begin}–{end}줄",
    "detail.output.truncated": "출력 잘림",
    "detail.plugins.count": "동적 플러그인 {count}개",
    "detail.providers.count": "검사 공급자 {count}개",
    "detail.ralph.limit": "회차 한도에 도달함",
    "detail.ralph.reportedBlocker": "작업자가 막힌 문제를 보고함",
    "detail.ralph.reportedComplete": "작업자가 완료를 보고함",
    "detail.receipt.alreadyFinished": "이미 끝남",
    "detail.receipt.cancel": "취소 요청됨",
    "detail.receipt.closed": "닫힘",
    "detail.receipt.closing": "닫는 중",
    "detail.receipt.delivered": "메시지 전달됨",
    "detail.receipt.interrupt": "중단 요청됨",
    "detail.receipt.signal": "시그널 전달됨",
    "detail.receipt.started": "시작됨",
    "detail.recordedResult": "기록된 결과",
    "detail.report.nextSteps": "남은 작업",
    "detail.schedule.count": "알림 {count}개",
    "detail.schedule.cron": "Cron {expression} ({zone})",
    "detail.schedule.daily": "매일 {time} ({zone})",
    "detail.schedule.deleted": "삭제됨",
    "detail.schedule.empty": "알림 없음",
    "detail.schedule.every": "{interval}마다",
    "detail.schedule.frequency": "반복",
    "detail.schedule.once": "한 번",
    "detail.schedule.overdue": "시간 지남, 세션 재개 대기 중",
    "detail.schedule.scheduled": "예약됨",
    "detail.schedule.weekly": "매주 {days}요일 {time} ({zone})",
    "detail.schedule.when": "예약 시각",
    "detail.seconds": "{count}초",
    "detail.state": "상태",
    "detail.status.accepted": "수락됨",
    "detail.status.completed": "완료",
    "detail.status.deleted": "삭제됨",
    "detail.status.exited": "종료됨",
    "detail.status.failed": "실패",
    "detail.status.idle": "유휴",
    "detail.status.inactive": "비활성",
    "detail.status.killed": "취소됨",
    "detail.status.provisioning": "준비 중",
    "detail.status.queued": "대기 중",
    "detail.status.ready": "준비됨",
    "detail.status.running": "실행 중",
    "detail.tasks.count": "팀 작업 {count}개",
    "detail.tasks.nextPage": "작업이 더 있습니다. 다음 커서는 {cursor}입니다",
    "detail.terminals.count": "터미널 {count}개",
    "detail.todo.completed": "완료",
    "detail.todo.empty": "할 일 목록이 비어 있습니다",
    "detail.todo.in_progress": "진행 중",
    "detail.todo.pending": "대기 중",
    "detail.trace.ancestors": "상위 세션",
    "detail.trace.derived": "파생 이벤트",
    "detail.trace.descendants": "하위 세션",
    "detail.trace.replacedBy": "대체한 항목",
    "detail.trace.replacementChain": "대체 체인",
    "detail.trace.replaces": "대체된 이벤트",
    "detail.trace.sources": "원본 이벤트",
    "detail.wait.changed": "변경 감지됨",
    "detail.wait.noProgress": "실행 중인 서브에이전트 없음",
    "detail.wait.timeout": "대기 시간 초과",
    "detail.wait.title": "서브에이전트 활동",
    "detail.weekday.1": "월",
    "detail.weekday.2": "화",
    "detail.weekday.3": "수",
    "detail.weekday.4": "목",
    "detail.weekday.5": "금",
    "detail.weekday.6": "토",
    "detail.weekday.7": "일",
    "detail.weekday.join": ", ",
    "detail.workflow.script": "워크플로 스크립트",
    "detail.yes": "예",
    "details.running": "실행 중…",
    "diff.collapseAria": "변경 사항 접기",
    "diff.expandAria": "변경 줄 {count}개 더 펼치기",
    "diff.expandRest": "… {count}줄 더 있음",
    "error.sessionInUse": "이 세션은 이미 사용 중입니다. 실행 중인 다른 DSH 인스턴스(dsh web이나 데스크톱 앱 등)가 쓰고 있을 수 있습니다. 다른 DSH 인스턴스를 종료하고 다시 시도해 주세요.",
    "file.label": "파일",
    "file.notStaged": "파일 업로드가 끝나지 않았습니다. 다시 추가한 뒤 시도해 주세요",
    "file.pending": "대기 중인 파일",
    "file.remove": "{name} 파일 제거",
    "file.retry": "{name} 파일 다시 업로드",
    "file.sessionUnavailable": "세션을 쓸 수 없어 파일을 업로드할 수 없습니다",
    "file.stillUploading": "파일을 아직 업로드하고 있습니다. 끝난 뒤에 보내 주세요",
    "file.uploadFailed": "업로드 실패, 클릭해 다시 시도",
    "file.uploading": "업로드하는 중…",
    "hero.chooseWorkspace": "워크스페이스 선택",
    "hero.headline": "미지의 세계로",
    "hero.preview": "프리뷰",
    "hint.goal": "오래 걸리는 작업의 목표를 적어 주세요",
    "hint.goal.active": "목표 진행 중: edit / pause / resume / clear",
    "hint.plan": "작업을 설명하면 계획을 세웁니다",
    "image.closePreview": "원본 이미지 미리보기 닫기",
    "image.dimensionTooLarge": "이미지 가로세로는 각각 {size}px 이하여야 합니다. 크기를 줄여 다시 시도해 주세요",
    "image.fileTooLarge": "이미지는 한 장당 {size}보다 작아야 합니다",
    "image.label": "이미지",
    "image.loadFailed": "이미지를 불러오지 못했습니다. 클릭해 다시 시도해 주세요",
    "image.loading": "이미지 불러오는 중…",
    "image.modelUnsupported": "현재 모델은 이미지를 지원하지 않습니다. 이미지를 지원하는 모델로 바꿔 주세요",
    "image.openOriginal": "원본 보기",
    "image.openOriginalLabel": "{label}, 클릭해 원본 보기",
    "image.original": "원본 이미지",
    "image.pending": "대기 중인 이미지",
    "image.preview": "원본 이미지 미리보기",
    "image.remove": "{name} 이미지 제거",
    "image.sendFailed": "이미지를 보내지 못했습니다({reason}). 다시 추가한 뒤 시도해 주세요",
    "image.tooMany": "메시지 하나에 이미지는 최대 {count}개까지 넣을 수 있습니다",
    "image.tooManyPixels": "이미지 해상도가 너무 높습니다. 압축한 뒤 다시 시도해 주세요",
    "image.totalTooLarge": "이미지 합계 크기가 {size} 한도를 넘습니다. 일부를 빼고 다시 시도해 주세요",
    "image.unsupportedType": "PNG, JPG, WebP, GIF 이미지만 지원합니다",
    "input.commands": "파일 추가 또는 명령 실행",
    "input.file": "파일",
    "input.send": "메시지 보내기",
    "input.send.queue": "대기열에 추가",
    "input.send.steer": "즉시 전달",
    "input.stop": "생성 중지",
    "placeholder.default": "메시지를 입력하거나 작업을 실행하세요. / 명령, @ 파일 또는 세션",
    "placeholder.hero": "만들고 싶은 것을 설명해 주세요. / 명령, @ 파일 또는 세션",
    "placeholder.parentOffline": "상위 세션이 오프라인이라 보낼 수 없습니다. 실행 중지는 할 수 있습니다",
    "placeholder.plan": "작업을 설명하면 계획을 세웁니다",
    "placeholder.steerQueue": "Cmd/Ctrl+Enter를 누르면 대기 중인 메시지를 모두 즉시 전달합니다",
    "placeholder.unavailable": "세션을 쓸 수 없음",
    "placeholder.workspace": "시작하려면 워크스페이스를 고르세요",
    "queue.cancelEdit": "편집 취소",
    "queue.count": "대기 중인 메시지 {n}개",
    "queue.edit": "대기 중인 메시지 편집",
    "queue.edit.unsupported": "텍스트가 아닌 내용이 있어 아직 편집할 수 없습니다",
    "queue.editFailed": "편집하지 못했습니다. 메시지를 이미 보내기 시작했을 수 있습니다.",
    "queue.file": "대기 중인 파일 {name}",
    "queue.image": "대기 중인 메시지 이미지",
    "queue.remove": "대기 중인 메시지 제거",
    "queue.removeFailed": "제거하지 못했습니다. 메시지를 이미 보내기 시작했을 수 있습니다.",
    "queue.save": "대기 중인 메시지 저장",
    "queue.sending": "보내는 중…",
    "queue.steer": "대기 중인 메시지 즉시 전달",
    "queue.steer.unavailable": "즉시 전달은 에이전트가 실행 중일 때만 쓸 수 있습니다",
    "queue.steerFailed": "즉시 전달하지 못했습니다. 다시 시도해 주세요.",
    "read.collapseAria": "내용 접기",
    "read.expandAria": "{count}줄 더 펼치기",
    "read.expandRest": "… {count}줄 더 있음",
    "read.window": "전체 {total}줄 중 {shown}줄 표시",
    "row.failed": "실패",
    "row.input": "입력",
    "row.inspect": "검사",
    "row.output": "출력",
    "row.preparing": "도구 호출 준비 중",
    "row.running": "실행 중",
    "row.stopped": "중지됨",
    "search.collapseAria": "결과 접기",
    "search.expandAria": "결과 {count}줄 더 펼치기",
    "search.expandRest": "… {count}줄 더 있음",
    "search.matches": "일치 {shown}개 · 파일 {files}개",
    "search.matches.truncated": "일치 {total}개 중 {shown}개 표시 · 파일 {files}개",
    "search.noResults": "결과 없음",
    "search.paths": "경로 {shown}개",
    "search.paths.truncated": "경로 {total}개 중 {shown}개 표시",
    "session.hierarchy": "세션 계층",
    "settings.enter.description": "에이전트가 실행 중일 때 Enter 키와 보내기 버튼이 하는 동작입니다. Cmd/Ctrl+Enter는 다른 쪽 동작을 합니다",
    "settings.enter.queue": "대기열",
    "settings.enter.steer": "즉시 전달",
    "settings.enter.title": "실행 중 보내기 동작",
    "shortcut.complementary": "대기열 / 즉시 전달 중 다른 쪽 동작 사용",
    "shortcut.mention": "참조 메뉴 열기",
    "shortcut.newline": "줄 바꿈",
    "shortcut.slash": "명령 메뉴 열기",
    "terminal.collapseAria": "출력 접기",
    "terminal.done": "완료",
    "terminal.exitCode": "종료 코드 {code}",
    "terminal.expandAria": "남은 출력 {n}줄 펼치기",
    "terminal.expandRest": "… {n}줄 더 있음",
    "terminal.failed": "실패",
    "terminal.noExitCode": "종료 코드 없음",
    "terminal.noOutput": "출력 없음",
    "terminal.running": "실행 중",
    "terminal.sendInput": "(입력 보냄)",
    "terminal.session": "터미널 {sessionId}",
    "terminal.signal": "시그널 {signal}",
    "todo.completed": "{done}/{total} 완료",
    "todo.diff.added": "{count}개 추가",
    "todo.diff.addedItem": "추가됨",
    "todo.diff.compare": "이전 목록과 달라진 점",
    "todo.diff.initial": "첫 목록",
    "todo.diff.movedItem": "순서 바뀜",
    "todo.diff.noChanges": "목록이 바뀌지 않았습니다",
    "todo.diff.removed": "{count}개 제거",
    "todo.diff.removedItem": "제거됨",
    "todo.diff.unavailable": "이전 목록을 볼 수 없음",
    "todo.diff.unchanged": "{count}개 그대로",
    "todo.diff.updated": "{count}개 업데이트",
    "todo.diff.updatedItem": "상태 바뀜",
    "todo.progress.active": "{active}개 진행 중",
    "todo.progress.done": "{done}개 완료",
    "todo.progress.pending": "{pending}개 대기 중",
    "todo.rowTitle": "할 일 목록 업데이트",
    "todo.status.completed": "완료",
    "todo.status.inProgress": "진행 중",
    "todo.status.pending": "대기 중",
    "todo.title": "할 일",
    "tool.autoReviewNotExecuted": "도구를 실행하지 않았습니다. 이유: {reason}",
    "tool.autoReviewReasonFallback": "자동 검토에서 이 작업을 허용하지 않았습니다",
    "tool.autoReviewRejected": "자동 검토에서 거부됨",
    "tool.preparing.content": "내용 준비 중 {kilobytes}KB",
    "tool.title.bash": "Bash",
    "tool.title.closeTerminal": "터미널 닫기",
    "tool.title.code": "코드",
    "tool.title.createGoal": "목표 만들기",
    "tool.title.createSchedule": "알림 만들기",
    "tool.title.createTeamTask": "팀 작업 만들기",
    "tool.title.deleteSchedule": "알림 삭제",
    "tool.title.edit": "편집",
    "tool.title.findDefinition": "정의 찾기",
    "tool.title.findImplementation": "구현 찾기",
    "tool.title.findReferences": "참조 찾기",
    "tool.title.generic": "도구 호출",
    "tool.title.getGoal": "목표 보기",
    "tool.title.getTeamTask": "팀 작업 읽기",
    "tool.title.glob": "Glob",
    "tool.title.grep": "Grep",
    "tool.title.hoverSymbol": "심볼 검사",
    "tool.title.inspect": "Cordis 환경 조회",
    "tool.title.inspectPlugins": "플러그인 검사",
    "tool.title.inspectProviders": "공급자 검사",
    "tool.title.interruptAgent": "에이전트 중단",
    "tool.title.killJob": "백그라운드 작업 취소",
    "tool.title.listAgents": "서브에이전트 목록",
    "tool.title.listJobs": "백그라운드 작업 목록",
    "tool.title.listModels": "모델 목록",
    "tool.title.listSchedules": "알림 목록",
    "tool.title.listTeamTasks": "팀 작업 목록",
    "tool.title.listTerminals": "터미널 목록",
    "tool.title.lsp": "코드 심볼 조회",
    "tool.title.openTerminal": "터미널 열기",
    "tool.title.pwsh": "Pwsh",
    "tool.title.queryRuntime": "런타임 조회",
    "tool.title.ralph": "ralph 루프 실행",
    "tool.title.read": "읽기",
    "tool.title.readEvent": "이벤트 읽기",
    "tool.title.readImage": "이미지 읽기",
    "tool.title.readJob": "작업 출력 읽기",
    "tool.title.readTerminal": "터미널 읽기",
    "tool.title.removeCordis": "Cordis 플러그인 제거",
    "tool.title.runCordis": "Cordis 플러그인 실행",
    "tool.title.search": "검색",
    "tool.title.searchEvents": "이벤트 검색",
    "tool.title.searchSessions": "세션 검색",
    "tool.title.sendMessage": "메시지 보내기",
    "tool.title.signalTerminal": "터미널에 시그널 보내기",
    "tool.title.spawnTeammate": "팀원 만들기",
    "tool.title.stopCordis": "Cordis 플러그인 중지",
    "tool.title.subagent": "서브에이전트 만들기",
    "tool.title.traceEvent": "이벤트 추적",
    "tool.title.traceSession": "세션 추적",
    "tool.title.updateGoal": "목표 업데이트",
    "tool.title.updateSchedule": "알림 업데이트",
    "tool.title.updateTeamTask": "팀 작업 업데이트",
    "tool.title.waitAgent": "서브에이전트 기다리기",
    "tool.title.webFetch": "가져오기",
    "tool.title.webSearch": "검색",
    "tool.title.workflow": "워크플로 실행",
    "tool.title.write": "쓰기",
    "web.contentTruncated": "내용 잘림",
    "web.http": "HTTP",
    "web.noResults": "결과를 찾지 못했습니다",
    "web.sourcesTruncated": "출처 목록 잘림"
  },
  "cordis": {
    "a11y.defining": "플러그인 정의 중",
    "a11y.failed": "정의 실패",
    "a11y.preparing": "Cordis 도구 호출 준비 중",
    "a11y.stopped": "정의 중단됨",
    "action.approve": "허용",
    "action.approveOnce": "이 버전만 허용",
    "action.approvePlugin": "이 플러그인의 이후 버전도 허용",
    "action.decline": "거부",
    "action.inspect": "검사",
    "action.remove": "제거",
    "action.retry": "다시 시도",
    "action.rollback": "되돌리기",
    "action.run": "실행",
    "action.stop": "중지",
    "body.clientCode": "클라이언트",
    "body.copied": "복사됨",
    "body.copy": "복사",
    "body.hostCode": "호스트",
    "body.output": "결과",
    "body.source": "플러그인 소스",
    "panel.approvals.aria": "Cordis 승인 요청",
    "panel.current": "현재: {packageId}",
    "panel.empty": "아직 정의한 플러그인이 없습니다",
    "panel.group.current": "이 세션",
    "panel.group.others": "다른 세션",
    "panel.hint": "실행 제어는 설정 위의 Cordis 패널에 있습니다",
    "panel.loading": "읽는 중…",
    "panel.next": "다음: {packageId}",
    "panel.plugins.aria": "Cordis 플러그인",
    "panel.readFailed": "플러그인 목록을 읽지 못했습니다: {message}",
    "panel.runningCount": "{count}개 실행 중",
    "panel.title": "Cordis 플러그인",
    "panel.trigger": "Cordis 플러그인",
    "panel.version": "버전",
    "purpose.missing": "(용도 설명 없음)",
    "render.failedAbdicated": "{slot} 영역을 렌더링하지 못해 기본 UI로 되돌렸습니다:",
    "render.failedHeld": "{slot} 영역을 렌더링하지 못했습니다:",
    "row.defineTitle": "Cordis 플러그인 등록",
    "row.removeTitle": "Cordis 플러그인 제거",
    "row.runTitle": "Cordis 플러그인 실행",
    "row.stopTitle": "Cordis 플러그인 중지",
    "row.updateTitle": "Cordis 플러그인 업데이트",
    "run.removed": "이 패키지는 더 이상 없습니다",
    "run.superseded": "아래에 더 새로운 실행 카드가 있습니다",
    "status.awaitingApproval": "승인 대기 중",
    "status.clientPending": "클라이언트 활성화 준비됨",
    "status.failed": "실행 실패",
    "status.idle": "준비됨",
    "status.removed": "제거됨",
    "status.running": "실행 중",
    "status.superseded": "새 실행 있음"
  },
  "feedback": {
    "action.dislike": "별로인 응답",
    "action.dislikeActive": "평가 취소",
    "action.like": "좋은 응답",
    "action.likeActive": "평가 취소",
    "category.instruction-following": "지시 이해와 수행",
    "category.other": "기타",
    "category.product-interaction": "제품 기능과 사용성",
    "category.resource-cost": "리소스 사용량과 비용",
    "category.security-privacy-permission": "보안, 개인정보, 권한",
    "category.service-stability": "안정성과 속도",
    "category.task-result": "작업 결과",
    "dialog.categories": "피드백 분류",
    "dialog.detail": "피드백 내용",
    "dialog.hint": "개선에 도움이 되도록 자세히 적어 주세요. 제출하면 현재 대화 로그도 함께 보냅니다.",
    "dialog.title": "피드백 보내기",
    "error.conflict": "다른 곳에서 피드백이 바뀌어 최신 상태를 표시합니다",
    "error.generic": "피드백을 저장하지 못했습니다",
    "error.load": "피드백을 불러오지 못했습니다",
    "error.noteTooLarge": "설명이 너무 깁니다. 줄인 뒤 다시 제출해 주세요",
    "toast.recorded": "피드백을 보내 주셔서 감사합니다"
  },
  "model": {
    "action.reload": "다시 불러오기",
    "command.description": "이 대화에 쓸 모델 선택",
    "command.label": "모델",
    "effort.providerDefault": "기본값",
    "empty.efforts": "이 모델은 추론 강도 단계를 제공하지 않습니다.",
    "empty.models": "사용할 수 있는 모델이 없습니다.",
    "error.action": "모델 작업 실패: {message}",
    "error.sessionInUse": "이 세션은 이미 사용 중입니다. 실행 중인 다른 DSH 인스턴스(dsh web이나 데스크톱 앱 등)가 쓰고 있을 수 있습니다. 다른 DSH 인스턴스를 종료하고 다시 시도해 주세요.",
    "menu.aria": "모델과 추론 강도",
    "menu.effort": "추론 강도",
    "menu.model": "모델",
    "option.loadError": "모델 목록을 불러오지 못했습니다: {message}",
    "provider.account": "DeepSeek 계정",
    "search.clear": "검색어 지우기",
    "search.empty": "일치하는 모델이 없습니다.",
    "search.placeholder": "모델 검색…",
    "status.loading": "모델 목록 새로 고치는 중…",
    "trigger.aria": "모델 선택, 현재 {model}",
    "trigger.ariaEffort": "모델 선택, 현재 {model}, 추론 강도 {effort}",
    "trigger.fallback": "모델 선택",
    "trigger.loading": "모델 불러오는 중…",
    "trigger.selectAria": "모델 선택",
    "warning.groupLoad": "{name} 불러오기 실패: {message}"
  },
  "permission.access": {
    "auto.badge": "실험",
    "auto.confirm.acknowledge": "이 위험을 이해했으며 계속하겠습니다",
    "auto.confirm.description": "자동 검토는 샌드박스 없이 실행됩니다. 네이티브 도구 호출과 PTC 내부 호출을 실행하기 전마다 현재 에이전트와 같은 모델이 허용 여부를 검토합니다. 모델이 거부한 호출은 직접 승인하거나 거부합니다. 실험 기능이라 동작을 잘못 허용하거나 거부할 수 있으며 토큰을 추가로 씁니다.",
    "auto.confirm.enable": "자동 검토 사용",
    "auto.confirm.title": "자동 검토(실험 기능)를 사용할까요?",
    "auto.description": "모든 네이티브 도구 호출과 PTC 내부 호출을 같은 모델이 먼저 검토(실험 기능)한 뒤 샌드박스 없이 실행합니다.",
    "auto.label": "자동 검토",
    "close": "닫기",
    "confirm.acknowledge": "위험을 이해했으며 계속하겠습니다",
    "confirm.cancel": "취소",
    "confirm.description": "전체 접근을 켜면 확인 절차가 줄어 에이전트가 민감한 작업, 파일 변경, 외부 명령 등을 더 많이 바로 실행합니다. 현재 작업을 신뢰할 수 있을 때만 쓰세요.",
    "confirm.enable": "전체 접근 사용",
    "confirm.title": "전체 접근을 사용할까요?",
    "mode": "접근 모드, 현재: {name}",
    "preset.fullAccess": "전체 접근",
    "preset.readOnly": "읽기 전용",
    "preset.workspaceWrite": "워크스페이스 쓰기"
  },
  "pluginManager": {
    "addPlugin": "플러그인 추가",
    "backToList": "플러그인 목록으로",
    "backToPackage": "{name} 화면으로 돌아가기",
    "bundlesTitle": "설치됨",
    "cancel": "취소",
    "close": "닫기",
    "configureRow": "{name} 설정",
    "confirmUninstall": "제거",
    "confirmUninstallDescription": "제거하면 이 플러그인이 제공하던 기능도 사라집니다.",
    "confirmUninstallTitle": "\"{name}\" 플러그인을 제거할까요?",
    "crumbRoot": "플러그인",
    "empty": "아직 설치한 플러그인이 없습니다.",
    "enableToggle": "{name} 사용",
    "error": "플러그인을 모두 읽지 못했습니다. 네트워크 문제일 수 있습니다",
    "failedDisable": "사용 중지하지 못했습니다: {reason}",
    "failedEnable": "사용 설정하지 못했습니다: {reason}",
    "failedRowDisable": "구성 요소를 사용 중지하지 못했습니다: {reason}",
    "failedRowEnable": "구성 요소를 사용 설정하지 못했습니다: {reason}",
    "failedUninstall": "제거하지 못했습니다: {reason}",
    "infoDescription": "여기서 공식 플러그인을 설정하고 다른 플러그인을 설치하거나 관리합니다. 기본 제공 플러그인 목록과 실행 상태는 설정 → 기본 제공 플러그인에서 볼 수 있습니다.",
    "infoLabel": "플러그인 안내",
    "installApplying": "구성을 적용하는 중입니다. 잠시 기다려 주세요…",
    "installApplyingCancellationError": "취소가 확인되지 않았습니다. 설치를 적용하고 있으니 결과를 기다려 주세요. {reason}",
    "installApprovalCaution": "신뢰하는 패키지만 허용하세요.",
    "installApprovalConsequence": "허용하면 스크립트가 현재 사용자 권한으로 이 컴퓨터에서 실행됩니다. 허용 설정은 이 프로필에 저장됩니다.",
    "installApprovalDescription": "이 패키지에는 pnpm이 실행하지 않은 설치 스크립트가 있습니다.",
    "installApprovalTitle": "설치 스크립트 실행 허용 필요",
    "installApproveAndRetry": "이 스크립트를 허용하고 다시 시도",
    "installAttempt": "{previous}에서 패키지를 받지 못해 {registry}에서 다시 시도합니다(레지스트리 {index}/{total})",
    "installAttemptBadge": "{index}번째 시도 · {registry}",
    "installAwaitingAcceptance": "호스트가 설치를 받아들이기를 기다리는 중입니다. 확인되면 취소를 자동으로 다시 시도합니다.",
    "installBackgroundApplying": "설치를 적용하는 중이라 취소할 수 없습니다. 설치 진행 상황을 확인하세요.",
    "installBackgroundDone": "설치를 마쳤습니다. 설치 세부 정보를 확인하세요.",
    "installBackgroundFailed": "설치하지 못했습니다. 설치 세부 정보를 확인하세요.",
    "installBackgroundUnconfirmed": "설치 상태가 확인되지 않았습니다. 설치 화면에서 자세한 내용을 확인하세요.",
    "installBackgroundUnknown": "설치 결과를 알 수 없습니다. 플러그인 목록을 확인하세요.",
    "installCancel": "설치 취소",
    "installCancelAndEdit": "설치를 취소하고 편집으로 돌아가기",
    "installCancelUnconfirmed": "설치가 멈췄는지 확인되지 않았습니다. 다시 취소하거나 설치 결과를 기다려 주세요. {reason}",
    "installCancelled": "설치를 취소했습니다. 플러그인은 사용 설정되지 않았으며 내려받은 파일이 남아 있을 수 있습니다",
    "installCancelledShort": "취소됨",
    "installCancelling": "설치를 멈추는 중…",
    "installChangeRegistry": "레지스트리 변경",
    "installChecking": "확인하는 중…",
    "installClose": "완료",
    "installCloseCancels": "설치 취소 후 닫기",
    "installDescription": "플러그인 패키지 이름, GitHub 저장소 주소 또는 로컬 디렉터리 경로를 입력하세요.",
    "installDetailsHide": "설치 세부 정보 숨기기",
    "installDetailsShow": "설치 세부 정보 보기",
    "installDoneApproved": "{names} 설치 스크립트를 허용했습니다",
    "installDoneNothing": "새 의존성 없이 설치를 마쳤습니다.",
    "installDoneRestart": "설치했습니다. 다음에 시작할 때 불러옵니다.",
    "installEdit": "편집",
    "installEditAria": "편집으로 돌아가기",
    "installEnableNow": "지금 사용",
    "installFailedTitle": "플러그인을 설치하지 못했습니다",
    "installFailureBuildBlocked": "설치를 계속하려면 의존성의 설치 스크립트 실행을 허용해야 합니다",
    "installFailureBuildBlockedManual": "pnpm이 설치 스크립트를 막았습니다. pnpm-workspace.yaml의 allowBuilds에서 허용한 뒤 다시 시도해 주세요",
    "installFailureDiskFull": "디스크가 가득 차서 설치를 멈췄습니다",
    "installFailureGeneric": "설치 중 문제가 생겼습니다. 자세한 내용은 세부 정보를 확인하세요",
    "installFailureIntegrity": "내려받은 패키지가 무결성 검사를 통과하지 못했습니다",
    "installFailureNetwork": "네트워크에 연결하지 못했습니다",
    "installFailureNetworkAll": "연결할 수 있는 레지스트리가 없습니다(시도한 곳: {registries}). 네트워크나 프록시 설정을 확인하거나 레지스트리를 바꾼 뒤 다시 시도해 주세요.",
    "installFailureNetworkHost": "{host}에 연결할 수 없습니다. GitHub 주소나 .tgz 링크는 레지스트리를 거치지 않으므로 이 컴퓨터에서 직접 또는 프록시를 통해 접속할 수 있어야 합니다. 플러그인이 npm에도 올라와 있다면 패키지 이름을 대신 입력하세요.",
    "installFailureNoMatchingVersion": "요청과 일치하는 버전이 없습니다",
    "installFailureNotFound": "해당 플러그인을 찾지 못했습니다",
    "installFailurePermission": "쓰기 권한이 없어 플러그인을 설치할 수 없습니다",
    "installFailurePnpmMissing": "pnpm을 찾지 못해 설치할 수 없습니다",
    "installFailureTimeout": "설치 시간이 초과되었습니다",
    "installGitTemplateHint": "실제 Git 저장소 주소로 바꾸세요.",
    "installGithubFailedDescription": "다른 설치 경로를 시도해 보세요.",
    "installGithubFailedTitle": "GitHub에 접속할 수 없음",
    "installGithubTimeoutTitle": "GitHub 연결 시간 초과",
    "installGuideExampleLabel": "예: ",
    "installGuideFill": "예시 사용",
    "installGuideFillAria": "{example} 예시 사용",
    "installGuideHide": "안내 숨기기",
    "installGuideIdExample": "dsh-plugin-whale-pet",
    "installGuideIdHint": "플러그인 패키지 이름은 npm 패키지 이름(dsh-xxx나 @author/plugin 형식)입니다. 커뮤니티 플러그인 README의 설치 명령에서 dsh plugin add 또는 pnpm add 뒤에 오는 부분입니다.",
    "installGuideIdTitle": "플러그인의 npm 패키지 이름 입력",
    "installGuideSafety": "신뢰하는 플러그인만 설치하세요. 플러그인은 현재 사용자 권한으로 실행되므로 DeepSeek Harness를 망가뜨리거나 데이터를 유출할 수 있습니다.",
    "installGuideToggle": "설치 안내와 예시",
    "installLocation": "설치 위치: {dir}",
    "installPackageLabel": "플러그인 패키지 이름",
    "installPathTemplateHint": "로컬 플러그인 디렉터리의 실제 경로로 바꾸세요.",
    "installProblemInstalled": "이미 설치된 플러그인입니다. 업그레이드하려면 제거한 뒤 다시 설치하세요",
    "installProblemInvalid": "설치할 수 있는 패키지 이름이나 주소가 아닙니다: {reason}",
    "installProblemNetwork": "플러그인 레지스트리에 연결할 수 없습니다. 네트워크를 확인하고 다시 시도해 주세요",
    "installProblemNetworkAll": "연결할 수 있는 레지스트리가 없습니다(시도한 곳: {registries}). 네트워크나 프록시 설정을 확인하거나 레지스트리를 바꿔 보세요",
    "installProblemNotBundle": "이 패키지는 번들을 선언하지 않아 플러그인으로 설치할 수 없습니다: {reason}",
    "installProblemNotFound": "해당 플러그인을 찾지 못했습니다",
    "installProblemNotPackage": "경로가 없거나 올바른 플러그인 패키지가 아닙니다",
    "installProblemShipped": "DSH에 포함된 플러그인입니다. DSH를 업그레이드하면 함께 업데이트됩니다",
    "installProblemUnknown": "플러그인을 조회하지 못했습니다: {reason}",
    "installReconcile": "설치 상태 확인",
    "installResultUnconfirmed": "설치 결과를 받지 못했습니다. 설치 상태를 확인하세요. {reason}",
    "installRetry": "다시 시도",
    "installRun": "설치",
    "installSpecLabel": "패키지 이름 또는 주소",
    "installSpecPlaceholder": "예: dsh-plugin-whale-pet",
    "installStarting": "설치 준비 중…",
    "installSubjectGit": "Git 저장소",
    "installSubjectPath": "로컬 디렉터리",
    "installSubjectTarball": "tarball 파일",
    "installTitle": "플러그인 추가",
    "installTryAnotherWay": "다른 방법 시도",
    "installUnconfirmedTitle": "설치 상태 확인 안 됨",
    "installUnknownDescription": "호스트에 이 요청 ID로 진행 중인 설치가 없습니다. 다시 시도하기 전에 플러그인 목록을 확인하세요.",
    "installUnknownTitle": "설치 결과를 알 수 없음",
    "installUpgradeNotice": "설치한 플러그인은 아직 자동으로 업데이트되지 않습니다. 업그레이드하려면 플러그인을 제거한 뒤 새 버전을 설치하세요. 업그레이드 방식은 이후 릴리스에서 계속 개선할 예정입니다.",
    "installUseGithubMirror": "중국 본토 미러 사용",
    "installVersion": "버전 {version}",
    "installViewTask": "설치 보기",
    "installedTitle": "설치됨",
    "installingTitle": "플러그인 설치 중…",
    "intro": "플러그인 설치, 사용 설정, 구성",
    "loading": "플러그인 읽는 중…",
    "metadataError": "패키지 메타데이터 오류: {error}",
    "officialTitle": "공식",
    "openDetail": "{name} 보기",
    "overriddenNotice": "{name} 설정을 저장했지만 우선순위가 더 높은 구성이 덮어써서 적용되지 않습니다",
    "panel": "플러그인",
    "partOff": "꺼짐",
    "partToggle": "구성 요소 {name} 사용",
    "partsCountFailed": "{count}개 실패",
    "partsCountOff": "{count}개 꺼짐",
    "partsCountRunning": "{count}개 실행 중",
    "partsCountTotal": "전체 {count}개",
    "partsEmpty": "이 플러그인 묶음에는 구성 요소가 없습니다.",
    "partsFilter": "구성 요소 필터",
    "partsFilterEmpty": "일치하는 구성 요소가 없습니다.",
    "partsLabel": "구성 요소",
    "reasonAmbiguousInstall": "의존성 변경만으로는 어떤 패키지가 설치되었는지 알 수 없습니다.",
    "reasonBundleInUse": "다른 구성에서 이 번들의 구성 요소를 아직 쓰고 있습니다. 먼저 그쪽을 꺼 주세요.",
    "reasonIncompatibleInstall": "이 DSH와 호환되는 플러그인 버전을 설치하세요.",
    "reasonIncompatibleInstalled": "제거한 뒤 이 DSH와 호환되는 버전을 설치하세요.",
    "reasonIncompatibleVersion": "{plugin} 플러그인은 DSH {runtime} 버전과 호환되지 않습니다(필요: {peers}). 실행하면 비정상 종료나 데이터 손실이 생길 수 있습니다.",
    "reasonIncompatibleVersionUnnamed": "이 플러그인은 실행 중인 DSH 버전과 호환되지 않습니다. 실행하면 비정상 종료나 데이터 손실이 생길 수 있습니다.",
    "reasonInvalidSpec": "올바른 패키지 이름이나 주소를 입력하세요.",
    "reasonLabel": "이유",
    "reasonManagementRequired": "플러그인 관리에 필요해 끄거나 제거할 수 없습니다.",
    "reasonNotBundle": "이 패키지는 번들을 선언하지 않아 플러그인으로 관리할 수 없습니다.",
    "reasonNotRemovable": "이 패키지는 프로필 소유가 아니거나 플러그인 관리에 필요합니다.",
    "reasonOperationError": "호스트에서 오류를 보고했습니다.",
    "reasonStaleApproval": "대기 중인 스크립트 허용 항목이 바뀌었습니다. 다시 설치해 새로 고치세요.",
    "reasonStopProfile": "이 프로필은 HMR 없이 실행됩니다. 프로필을 멈추고 dsh plugin으로 패키지를 제거하세요.",
    "reasonUnaddressable": "프로필 패치에서 이 항목 하나만 정확히 가리킬 수 없습니다.",
    "reasonUnknownPlugin": "해당 플러그인이 없습니다.",
    "refresh": "새로 고침",
    "refreshError": "새로 고치지 못했습니다. 다시 시도해 주세요.",
    "registryCustom": "사용자 지정 주소",
    "registryCustomHint": "http:// 또는 https://로 시작하는 사내 또는 비공개 npm 레지스트리 주소를 입력하세요. 로그인이 필요하면 이 컴퓨터의 ~/.npmrc에 자격 증명을 저장하세요.",
    "registryCustomInvalid": "http:// 또는 https://로 시작하는 주소를 입력하세요",
    "registryCustomPlaceholder": "https://npm.example.com/",
    "registryDefault": "기본 레지스트리",
    "registryLegend": "플러그인을 내려받을 npm 레지스트리",
    "registryListSeparator": ", ",
    "registryNpmmirror": "중국 본토 미러",
    "registryOfficial": "공식 npm 레지스트리",
    "registryToggle": "레지스트리",
    "restartNotice": "변경 사항은 다음에 시작할 때 적용됩니다",
    "retry": "다시 시도",
    "rowPhaseActive": "실행 중",
    "rowPhaseFailed": "문제 있음",
    "rowPhaseLoading": "불러오는 중",
    "rowPhasePending": "의존성 기다리는 중",
    "rowPhaseUnloading": "언로드 중",
    "rowStateIdle": "실행 중 아님",
    "sentenceSeparator": " ",
    "statusBeta": "실험 기능",
    "statusProblem": "문제 있음",
    "terminalCollapse": "접기",
    "terminalCollapseAria": "출력 접기",
    "terminalCopied": "복사됨",
    "terminalCopy": "복사",
    "terminalDone": "완료",
    "terminalExitCode": "종료 코드 {code}",
    "terminalExpand": "… {n}줄 더 있음",
    "terminalExpandAria": "남은 출력 {n}줄 펼치기",
    "terminalFailed": "실패",
    "terminalNoExitCode": "종료 코드 없음",
    "terminalNoOutput": "출력 없음",
    "terminalRunning": "실행 중",
    "terminalSignal": "시그널 {signal}",
    "title": "플러그인",
    "unavailable": "이 배포 환경에는 관리할 수 있는 프로필이 없어 여기서 플러그인을 설치하거나 켜고 끌 수 없습니다.",
    "uninstall": "제거",
    "uninstallLabel": "{name} 제거",
    "versionTag": "v{version}"
  },
  "question": {
    "action.next": "다음",
    "action.skip": "건너뛰기",
    "custom.placeholder": "답변 입력",
    "error.incomplete": "이 질문에 먼저 답해 주세요.",
    "error.resubmit": "작업이 계속되기 전에 답변이 도착하지 않았습니다. 다시 제출해 주세요.",
    "error.unanswered": "옵션을 고르거나 직접 답을 입력해 주세요.",
    "error.unavailable": "지금은 제출할 수 없습니다. 잠시 뒤 다시 시도해 주세요.",
    "nav.cancel": "모든 질문 닫기",
    "nav.close": "패널 닫기(도구 호출에서 다시 열 수 있음)",
    "nav.maximize": "질문 카드 펼치기",
    "nav.minimize": "질문 카드 접기",
    "nav.next": "다음 질문",
    "nav.prev": "이전 질문",
    "option.recommended": "추천",
    "plan.approve": "승인",
    "plan.decline": "거절",
    "plan.discuss": "수정 요청",
    "plan.header": "계획 검토",
    "reply.answerLabel": "답변: ",
    "reply.close": "질문 세부 정보 닫기",
    "reply.label": "앞선 대기 중인 질문에 답하기",
    "reply.open": "질문 세부 정보 열기",
    "reply.skipped": "건너뜀",
    "review.skipped": "이 질문은 건너뛰었습니다.",
    "review.status": "답변함",
    "status.sent": "답변을 보냈지만 패널을 닫지 못했습니다.",
    "wait.continued": "작업은 계속됨, 아직 답할 수 있음",
    "wait.countdown": "{seconds}초 뒤 계속",
    "wait.held": "답변을 기다리는 중",
    "wait.paused": "일시 중지됨 · {seconds}초 남음",
    "wait.takeTime": "천천히 답하기"
  },
  "reference": {
    "candidate.noCwd": "(작업 디렉터리 없음)",
    "crumb.root": "워크스페이스",
    "section.files": "파일 및 폴더",
    "section.sessions": "세션",
    "section.subagents": "서브에이전트",
    "time.days": "{n}일",
    "time.hours": "{n}시간",
    "time.minutes": "{n}분",
    "time.months": "{n}개월",
    "time.now": "방금",
    "time.years": "{n}년"
  },
  "settings": {
    "close": "닫기",
    "connection.connected": "연결됨",
    "connection.connecting": "다시 연결하는 중",
    "connection.error": "연결 끊김",
    "connection.reconnect": "연결이 끊겼습니다. 지금 다시 연결",
    "connection.restart": "다시 연결하는 중입니다. 지금 다시 연결",
    "desktop.update.available": "업데이트",
    "desktop.update.checkFailed": "업데이트를 확인하지 못했습니다. 잠시 뒤 다시 시도해 주세요.",
    "desktop.update.checkNetworkFailed": "업데이트를 확인하지 못했습니다. 네트워크 연결을 확인하고 다시 시도해 주세요.",
    "desktop.update.checking": "업데이트 확인 중…",
    "desktop.update.downloadDetail": "업데이트 내려받는 중: {percent}%\n대상 버전: {version}",
    "desktop.update.downloadFailed": "업데이트를 내려받지 못했습니다. 다시 시도해 주세요.",
    "desktop.update.downloadNetworkFailed": "업데이트를 내려받지 못했습니다. 네트워크 연결을 확인하고 다시 시도해 주세요.",
    "desktop.update.installFailed": "업데이트를 설치하지 못했습니다. 잠시 뒤 다시 시도해 주세요.",
    "desktop.update.installNetworkFailed": "업데이트를 설치하지 못했습니다. 네트워크 연결을 확인하고 다시 시도해 주세요.",
    "desktop.update.installing": "다시 시작할 준비 중…",
    "desktop.update.progress": "{percent}%",
    "desktop.update.ready": "설치 후 다시 시작",
    "desktop.update.retry": "업데이트 다시 시도",
    "desktop.update.stopFailed": "작업을 안전하게 멈추지 못해 업데이트를 설치하지 않았습니다. 잠시 뒤 다시 시도해 주세요.",
    "desktop.update.tasksChanged": "새 작업이 시작되었습니다. 작업을 멈추고 업데이트하려면 다시 확인해 주세요.",
    "desktop.update.tasksUnavailable": "작업 상태를 알 수 없습니다. 워크스페이스가 준비되면 다시 업데이트해 주세요.",
    "desktop.update.verifying": "업데이트 파일 확인 중…",
    "desktop.update.versionDetail": "{label}: {version}",
    "developerTools.description": "실행 기록, 코드 변경 사항, 모든 에이전트 프리셋을 표시합니다",
    "developerTools.error": "저장하지 못했습니다. 다시 시도해 주세요.",
    "developerTools.title": "코딩 보기 표시",
    "general.currentVersion": "현재 버전: {version}",
    "general.nav": "일반",
    "openDocument": "설정 파일 열기",
    "openDocument.error": "설정 파일을 열 수 없습니다",
    "shortcut.open": "설정 열기",
    "title": "설정",
    "trigger": "설정"
  },
  "settings.account": {
    "accountInfo": "계정 정보 더 보기",
    "addApiKey": "API 키 추가",
    "backToHarness": "DeepSeek Harness로 돌아가기",
    "balance": "충전 잔액",
    "balanceSignedOut": "로그인 후 확인",
    "balanceUnavailable": "플랫폼에서 확인",
    "bonusBalance": "지급 잔액",
    "bonusNoticeTitle": "보너스 지급됨",
    "browserDescription": ". 복사한 링크를 브라우저에서 열어 로그인을 마쳐 주세요.",
    "browserPrompt": "페이지가 자동으로 열리지 않았나요? ",
    "browserTitle": "로그인 기다리는 중",
    "cancel": "취소",
    "close": "닫기",
    "completing": "로그인 마무리하는 중…",
    "contactUs": "피드백",
    "copiedLink": "링크 복사됨",
    "copyFailed": "복사 실패",
    "copyLink": "로그인 링크 복사",
    "expired": "로그인이 만료되었습니다. 다시 시도해 주세요.",
    "failed": "작업을 마치지 못했습니다. 다시 시도해 주세요.",
    "failureTitle": "로그인할 수 없음",
    "initializing": "로그인 시작하는 중…",
    "loading": "불러오는 중…",
    "loginDescription": "DeepSeek 계정으로 로그인하거나 API 키를 추가해 시작하세요. 프로젝트와 파일은 이 컴퓨터에 저장됩니다.",
    "loginTitle": "시작하기",
    "menu": "계정 메뉴",
    "modelSignInRequired": "모델을 쓸 수 없습니다. 로그인한 뒤 다시 시도해 주세요.",
    "more": "더 보기",
    "nav": "계정",
    "onboardingArtworkLocale": "ko",
    "onboardingBack": "뒤로",
    "onboardingBrand": "DeepSeek Harness",
    "onboardingCompact": "결과만",
    "onboardingCompactDescription": "깔끔하고 단순한 화면에서 결과만 봅니다",
    "onboardingContinue": "계속",
    "onboardingCredit": "크레딧 충전",
    "onboardingCreditDescription": "DeepSeek Harness는 모델과 도구가 쓴 토큰만큼 크레딧을 차감합니다. 작업이 중간에 멈추지 않도록 크레딧을 미리 충전해 두세요. 잔액은 에이전트가 작업할 때만 쓰입니다.",
    "onboardingDetailed": "모든 과정",
    "onboardingDetailedDescription": "전체 과정을 보여 줘서 디버깅과 문제 해결이 쉽습니다",
    "onboardingDevelopment": "코딩과 개발",
    "onboardingDevelopmentDescription": "코드 수정, 디버깅, 명령 실행, 프로젝트 파일 관리 등",
    "onboardingEnter": "앱 열기",
    "onboardingFundedTopUp": "크레딧 충전",
    "onboardingGoTopUp": "크레딧 충전",
    "onboardingIntroduction": "DeepSeek Harness는 로컬 폴더에서 일하며 도구로 컴퓨터의 파일을 읽고 씁니다. 자료 조사와 정리, 문서와 스프레드시트 작성, 코드 작성, 문제 해결 등을 도와줍니다.",
    "onboardingKeepSetting": "설정 계속하기",
    "onboardingLater": "다음",
    "onboardingLoading": "설정 불러오는 중…",
    "onboardingNoCreditDescription": "크레딧이 없으면 DeepSeek Harness에서 새 작업을 시작할 수 없습니다. 나중에 설정 → 계정에서 충전할 수 있습니다.",
    "onboardingNoCreditTitle": "크레딧 충전을 건너뛸까요?",
    "onboardingOffice": "사무와 창작",
    "onboardingOfficeDescription": "문서 편집, 데이터 정리, 프레젠테이션 만들기 등",
    "onboardingProcess": "작업 과정을 얼마나 자세히 볼까요?",
    "onboardingProcessDescription": "진행 상황을 보여 주는 방식만 바뀌고 DeepSeek Harness가 할 수 있는 일은 그대로입니다.",
    "onboardingPurposeDescription": "작업 방식에 맞게 화면과 도구를 조정합니다.",
    "onboardingPurposePrefix": "어떤 일에",
    "onboardingPurposeSuffix": "도움이 필요하신가요?",
    "onboardingRetry": "다시 시도",
    "onboardingSaveFailed": "설정을 저장하지 못했습니다. 다시 시도해 주세요.",
    "onboardingSkip": "건너뛰기",
    "onboardingSkipDescription": "진행 상황, 성능, 사용량 표시 방식이나 코딩 도구 사용 여부는 언제든 설정 → 일반에서 바꿀 수 있습니다.",
    "onboardingSkipTitle": "설정을 건너뛸까요?",
    "onboardingStandard": "핵심만",
    "onboardingStandardDescription": "결과 위주로 보고, 중요한 단계와 동작만 표시합니다",
    "onboardingStart": "시작하기",
    "onboardingTopUp": "크레딧 충전",
    "onboardingUnderstood": "확인",
    "onboardingWelcome": "처음 만나는",
    "open": "브라우저 열기",
    "platformFailed": "작업을 마치지 못했습니다. 다시 시도해 주세요.",
    "platformRetry": "다시 시도",
    "profileUnavailable": "아직 계정 정보를 볼 수 없습니다.",
    "quotaDescription": "잔액이 없어 이 계정으로는 DeepSeek Harness에서 새 작업을 시작할 수 없습니다. 지금 충전할까요? 나중에 설정 → 계정에서 충전해도 됩니다.",
    "quotaTitle": "잔액 없음",
    "quotaTopUp": "충전",
    "retry": "다시 로그인",
    "sessionExpired": "계정에서 로그아웃되었습니다. 다시 로그인해 주세요.",
    "settings": "설정",
    "settingsSignedOutDescription": "DeepSeek Harness에 로그인하면 전용 API 키를 받을 수 있습니다",
    "settingsSignedOutTitle": "DeepSeek Harness에 로그인하지 않았습니다",
    "signIn": "로그인",
    "signInDescription": "DeepSeek 계정으로 시작하세요.",
    "signOut": "로그아웃",
    "signOutDescription": "로그아웃해도 데이터는 삭제되지 않습니다. 이 계정으로 다시 로그인할 수 있습니다.",
    "signOutRunningDescription": "실행 중인 작업이 있습니다. 로그아웃하면 작업이 중단됩니다. 지금 로그아웃할까요?",
    "signOutUnknownDescription": "실행 중인 작업을 확인하지 못했습니다. 로그아웃하면 이 계정을 쓰는 작업이 중단될 수 있습니다. 지금 로그아웃할까요?",
    "signedIn": "DeepSeek에 로그인됨",
    "signedOut": "로그인하지 않음",
    "timeoutDescription": "계속하려면 다시 로그인해 주세요.",
    "timeoutTitle": "로그인 시간 초과",
    "topUp": "충전",
    "usage": "사용량 보기",
    "waiting": "브라우저에서 계속하세요"
  },
  "settings.agentLoop": {
    "description": "에이전트가 도구 호출을 처리하는 방식을 정합니다.",
    "invalidNumber": "숫자를 입력하거나, 기본값을 쓰려면 비워 두세요.",
    "maxParallel": "병렬 도구 호출",
    "maxParallelHint": "한 단계 안에서 동시에 실행할 수 있는 병렬 안전 호출의 최대 개수입니다.",
    "overridden": "변경됨",
    "readOnly": "이 배포 환경에서는 설정이 읽기 전용입니다.",
    "reset": "기본값으로 되돌리기",
    "save": "저장",
    "saveFailed": "배포 환경에서 이 값을 받아들이지 않았습니다. 고칠 수 있도록 입력한 값은 그대로 두었습니다.",
    "saving": "저장하는 중…",
    "title": "에이전트 루프",
    "unavailable": "이 플러그인을 불러오지 않아 지금은 설정할 수 없습니다."
  },
  "settings.agentPreset": {
    "brokenBadge": "불러오지 못함",
    "builtInGroup": "기본 제공",
    "close": "닫기",
    "creatorDraft": "에이전트와 함께 프리셋 만들기",
    "customGroup": "사용자 지정",
    "guideCopied": "복사됨",
    "guideCopy": "복사",
    "guideCordisExplanation": "### 만들 수 있는 것\n\n크리에이터 모드에는 표준 작업 도구와 함께 런타임 검사, 영구 플러그인 관리, Cordis 플러그인과 에이전트 프리셋 작성 안내가 들어 있습니다. 기능이나 UI를 더하는 플러그인을 만들 수도 있고 특정 작업에 맞게 도구와 프롬프트를 묶은 프리셋을 만들 수도 있습니다.\n\n### 플러그인과 모드\n\n플러그인은 도구, 서비스 연결, UI 항목처럼 DSH에 기능을 더합니다. 모드는 에이전트 프리셋으로, 작업에 쓸 도구를 고르고 에이전트가 일하는 방식을 정합니다. 사용자 지정 프리셋에 플러그인을 넣을 수 있습니다.\n\n### 결과가 적용되는 방식\n\n소스 코드를 만든 뒤 설치와 검증까지 하도록 에이전트에게 요청하세요. 플러그인은 바뀌는 내용에 따라 바로 적용되기도 하고 다시 시작해야 적용되기도 합니다. 새로 만든 프리셋은 새 작업을 시작할 때 고를 수 있습니다.",
    "guideCordisIntro": "새 작업에서 크리에이터 모드를 고르세요. 원하는 기능, 그 기능이 나타날 위치, 확인 방법을 설명해 주세요.",
    "guideCordisUsage": "### UI 추가하기\n\n> 사이드바에 프로젝트 노트 항목을 추가하는 DSH 플러그인을 만들어 주세요. 이 워크스페이스의 Markdown 파일을 둘러보고 고른 노트를 미리 볼 수 있게 해 주세요. 설치하고 페이지가 열리는지 확인해 주세요.\n\n예상 결과: 항목과 미리보기 페이지가 동작하는 설치된 플러그인, 그리고 남은 활성화 단계가 있다면 그 안내.\n\n### 도구 추가하기\n\n> 이 프로젝트의 테스트 보고서를 읽고 실패한 테스트를 요약하는 도구가 들어 있는 플러그인을 만들어 주세요. 등록한 다음 샘플 보고서로 확인해 주세요.\n\n예상 결과: 호출할 수 있는 도구가 든 플러그인과 확인을 마친 샘플 호출.\n\n### 나만의 모드 만들기\n\n> 표준 모드를 바탕으로 “코드 리뷰” 모드를 만들어 주세요. 잠재적인 버그와 빠진 테스트를 먼저 살피고 파일 경로와 줄 번호를 밝혀 주세요. 파일을 고치기 전에는 물어보게 해 주세요. 선택할 수 있는 프리셋으로 저장해 주세요.\n\n예상 결과: 새 작업에 쓸 사용자 지정 프리셋. 이 리뷰 지침은 에이전트의 방향을 잡아 줄 뿐입니다. 실제로 실행할 수 있는 동작은 권한 설정이 정합니다.",
    "guideExampleTask": "예시 작업",
    "guideFootnotes": "각주",
    "guideMinimalExplanation": "### 포함된 것\n\n상태가 유지되는 셸 도구 하나와 고정된 시스템 프롬프트입니다. 이 기본 프리셋은 스킬, 계획, 컨텍스트 압축, 표준 런타임 컨텍스트를 불러오지 않습니다.\n\n### 언제 고를까\n\n실험과 비교의 기준선으로 쓰세요. 셸 명령으로 파일을 읽고 스크립트를 실행할 수는 있지만 긴 작업을 관리하는 기본 기능은 적습니다. 도구가 적다고 해서 처음 쓰는 사람에게 꼭 더 쉬운 것은 아닙니다.",
    "guideMinimalIntro": "새 작업에서 최소 모드를 고르세요. 비교할 때는 실행마다 모델, 권한, 입력, 시작 시점의 워크스페이스 상태를 똑같이 맞추세요.",
    "guideMinimalUsage": "### 작은 버그 수정으로 성능 비교하기\n\n> 이 프로젝트의 테스트를 실행하고 실패 원인을 찾아 가장 작은 수정으로 고쳐 주세요. 관련 테스트를 다시 실행하고 결과를 알려 주세요.\n\n같은 시작 상태에서 같은 작업을 표준 모드와 최소 모드로 따로 실행하세요. 작업 완료 여부, 도구 호출, 바뀐 결과를 비교합니다. 최소 모드는 터미널 명령으로 작업합니다.",
    "guidePtcExplanation": "### 도구를 호출하는 방식\n\nPTC는 Programmatic Tool Calling(프로그래밍 방식 도구 호출)을 뜻합니다. 이 기본 프리셋에서 에이전트는 run_code로 TypeScript 프로그램을 작성합니다. 이 프로그램이 생성된 SDK를 통해 도구를 호출합니다. 프로그램에서는 반복문, 조건문, 오류 처리를 쓸 수 있고 필요하면 여러 호출을 동시에 실행합니다.\n\n### 모델에 전달되는 것\n\n도구 결과는 먼저 프로그램에 전달되고 프로그램이 이를 거르거나 합칠 수 있습니다. 모델은 프로그램이 출력하거나 반환한 내용을 받습니다. 이미지 결과는 따로 첨부됩니다. 중첩된 도구 호출도 기록되고 도구 권한을 그대로 따릅니다.\n\n### 표준 모드와 비교\n\n두 모드 모두 코딩과 일괄 작업을 처리할 수 있습니다. 표준 모드는 개별 도구를 직접 노출하고 PTC는 도구 호출을 코드로 구성합니다. 현재 PTC 프리셋에서는 워크플로 도구가 꺼져 있습니다. 속도와 토큰 사용량은 작업 내용과 프로그램이 결과를 다루는 방식에 따라 달라집니다.",
    "guidePtcIntro": "새 작업을 시작할 때 PTC 모드를 고르세요. 입력 파일, 처리 규칙, 출력 형식을 정해 주면 코드는 에이전트가 작성합니다.",
    "guidePtcUsage": "### 설정 파일 한꺼번에 검사하기\n\n> configs/에 있는 JSON 파일을 모두 검사해 주세요. schema.json을 기준으로 빠진 필수 필드와 잘못된 값을 찾아 주세요. 문제 하나당 한 행으로 CSV를 저장해 주세요. 읽을 수 없는 파일은 보고서에 넣고 나머지는 계속 검사해 주세요. 원본 파일은 바꾸지 마세요.\n\n예상 결과: 문제 요약과 CSV 보고서. 프로그램은 같은 검사를 반복하고 개별 실패를 처리하며 결과를 모을 수 있습니다.\n\n### 오류 로그 요약하기\n\n> logs/에 있는 로그 파일을 분석해 주세요. 오류를 서비스별, 오류 유형별로 묶어 주세요. 가장 자주 나오는 그룹 열 개와 그룹마다 예시를 하나씩 보여 주세요. 전체 집계는 CSV로 저장해 주세요.\n\n예상 결과: 상위 오류 그룹과 전체 집계 표. 중간 데이터는 요약이 모델에 전달되기 전에 프로그램 안에서 집계할 수 있습니다.",
    "guideSections": "안내 목차",
    "guideStandardExplanation": "### 동작 방식\n\n에이전트가 도구를 직접 호출해 파일 읽기와 편집, 검색, 터미널 명령 실행을 합니다. 스킬, 계획, 목표, 서브에이전트, 워크플로, 컨텍스트 압축이 들어 있습니다.\n\n### 언제 고를까\n\n일상적인 코딩, 파일 작업, 자료 조사는 여기서 시작하세요. 표준 모드도 스크립트를 작성해 파일을 일괄 처리할 수 있습니다. PTC는 도구 호출을 구성하는 방식을 바꿀 뿐입니다. 일괄 작업에 꼭 필요한 것은 아닙니다.",
    "guideStandardIntro": "새 작업을 시작할 때 표준 모드를 고르세요. 이루려는 목표를 설명하고 관련 파일과 결과 확인 방법을 알려 주세요.",
    "guideStandardUsage": "### 버그 고치기\n\n> 검색 폼을 두 번 제출하면 결과가 사라지는 이유를 찾아 주세요. 고친 다음 관련 테스트를 실행해 주세요. 원인과 바뀐 내용을 설명해 주세요.\n\n예상 결과: 코드 변경, 관련 테스트 결과, 원인 설명.\n\n### 프로젝트 노트 정리하기\n\n> 이 프로젝트의 Markdown 노트를 읽어 주세요. 합의된 결정과 아직 열린 질문을 원본 파일 링크와 함께 요약해 주세요.\n\n예상 결과: 원래 노트와 대조해 볼 수 있는 참조가 달린 요약.",
    "headerHint": "이 작업을 시작할 때 고른 에이전트 프리셋",
    "howToUse": "사용법",
    "inUse": "새 작업 기본값",
    "modeExplanation": "모드 설명",
    "nav": "에이전트 프리셋",
    "noDescription": "설명이 없습니다.",
    "presetCordisDescription": "대화로 DSH를 원하는 대로 바꿉니다. 에이전트가 기능이나 UI를 더하는 플러그인을 작성하게 하거나 도구와 프롬프트를 묶어 나만의 모드를 만들 수 있습니다.",
    "presetCordisName": "크리에이터 모드",
    "presetMinimalDescription": "에이전트가 터미널 도구 하나로만 작업합니다. 기본 성능을 시험하고 비교할 때 좋습니다.",
    "presetMinimalName": "최소 모드",
    "presetPtcDescription": "표준 모드의 기능을 모두 포함합니다. 도구를 일괄로 호출한 뒤 결과를 필터링, 정리, 중복 제거, 집계, 요약하는 작업에 더 잘 맞습니다.",
    "presetPtcName": "PTC 모드",
    "presetStandardDescription": "코드, 파일, 정보를 다룹니다. 필요에 따라 검색, 편집, 터미널 명령 같은 도구를 쓰며 대부분의 작업에 알맞습니다.",
    "presetStandardName": "표준 모드",
    "seatHint": "새 작업에 쓸 에이전트 프리셋을 고르세요",
    "sectionIntro": "에이전트가 쓸 도구와 일하는 방식을 고릅니다. 일상 작업에는 표준 모드를, DSH에 기능을 더하려면 크리에이터 모드를 쓰세요.",
    "setDefault": "새 작업 기본값으로 설정",
    "switchRefused": "{name} 프리셋으로 바꾸지 못했습니다: {reason}",
    "view": "구성 보기"
  },
  "settings.locale": {
    "language.title": "언어"
  },
  "settings.models": {
    "add": "모델 공급자 추가",
    "addCatalog": "서드파티 모델 공급자",
    "addCatalogExhausted": "목록에 있는 공급자를 모두 구성했습니다.",
    "addCatalogHint": "기본 제공 목록에서 OpenAI, Anthropic, Kimi 등 공급자를 고르고 API 키를 입력합니다.",
    "addCustom": "사용자 지정 모델 API",
    "addCustomHint": "중계 서버, 자체 호스팅 서버 등 OpenAI 또는 Anthropic 호환 엔드포인트를 기본 URL, 프로토콜, 모델로 연결합니다.",
    "addCustomUnavailable": "선언할 수 있는 API 프로토콜이 없습니다.",
    "addMode": "추가 방법",
    "addModel": "모델 추가",
    "advancedHint": "다른 필드는 cordis.patch.yml에 있습니다. 해당 부분을 직접 편집하세요.",
    "apply": "적용",
    "applying": "적용하는 중…",
    "baseUrl": "기본 URL",
    "baseUrlDefault": "공급자 기본값",
    "cancel": "취소",
    "close": "닫기",
    "conflict": "이 카드를 연 사이에 다른 곳에서 설정이 바뀌었습니다. 닫았다가 다시 열어 현재 값을 편집하세요.",
    "contextWindow": "컨텍스트 창",
    "contextWindowPlaceholder": "공급자 기본값 사용",
    "create": "공급자 만들기",
    "creating": "만드는 중…",
    "credentialConfigured": "API 키 구성됨",
    "credentialMissing": "API 키 없음",
    "customAnthropicBaseUrlPlaceholder": "https://gateway.example",
    "customApi": "API 프로토콜",
    "customApiUnset": "선택되지 않음",
    "customBaseUrlInvalid": "올바른 HTTP 또는 HTTPS URL을 입력하세요.",
    "customBaseUrlPlaceholder": "https://gateway.example/v1",
    "customDisplayName": "표시 이름",
    "customNeedsBaseUrl": "사용자 지정 공급자에는 기본 URL이 필요합니다.",
    "customNeedsModels": "사용자 지정 공급자에는 모델이 하나 이상 있어야 합니다.",
    "customRoute": "공급자 ID",
    "customRouteHint": "영문 소문자로 시작하는 식별자입니다. 요청과 자격 증명 이름에서 이 공급자를 구분하므로 다른 공급자와 겹치면 안 됩니다.",
    "customRouteInvalid": "영문 소문자로 시작하고, 이어서 영문 소문자, 숫자, 하이픈만 쓰세요.",
    "customRouteTaken": "이 ID를 쓰는 공급자가 이미 있습니다.",
    "customTag": "사용자 지정",
    "customized": "변경한 설정",
    "deepSeekAccount": "DeepSeek 계정",
    "deepSeekBaseUrl": "https://api.deepseek.com/anthropic",
    "deepSeekEndpointHint": "Anthropic Messages와 호환되는 API 엔드포인트를 쓰세요.",
    "deleteConfirm": "{provider} 삭제",
    "deleteDescription": "{provider} 공급자를 삭제하면 구성이 제거됩니다. 이 공급자가 쓰는 자격 증명은 다른 곳에서 관리하므로 그대로 남습니다.",
    "deleteDescriptionWithCredential": "{provider} 공급자를 삭제하면 구성과 저장된 API 키가 제거됩니다.",
    "deleteTitle": "{provider} 공급자를 삭제할까요?",
    "deleting": "{provider} 삭제하는 중…",
    "edit": "편집",
    "editProvider": "{provider} 편집",
    "fetchAdopt": "선택한 모델 추가",
    "fetchDescription": "이 공급자에서 쓸 수 있는 모델입니다. 추가할 모델을 고르세요.",
    "fetchDeselectAll": "모두 선택 해제",
    "fetchEmpty": "공급자가 알려 준 모델이 없습니다. 직접 추가하세요.",
    "fetchModels": "사용 가능한 모델 가져오기",
    "fetchNeedsBaseUrl": "기본 URL을 먼저 입력한 뒤 가져오세요.",
    "fetchNoMatches": "일치하는 모델이 없습니다.",
    "fetchSearch": "모델 검색",
    "fetchSelectAll": "모두 선택",
    "fetchTitle": "추가할 모델 선택",
    "fetching": "공급자에 요청하는 중…",
    "intro": "아래 공급자의 모델을 쓰려면 API 키를 입력하세요.",
    "keyBlank": "API 키를 입력하세요. 저장된 키를 그대로 쓰려면 비워 두세요.",
    "keyBlankNew": "API 키를 입력하세요. 이 공급자가 다른 방식으로 인증한다면 비워 두세요.",
    "keyEnvLocked": "실행 환경에서 제공됨(읽기 전용)",
    "keyIllegalCharacters": "API 키 형식이 올바르지 않습니다. 다시 확인해 주세요.",
    "keyInput": "API 키",
    "keyPlaceholder": "API 키 입력",
    "keyPlaceholderNative": "API 키를 입력하거나, 환경 인증을 쓰려면 비워 두세요",
    "keyRequired": "계속하려면 API 키를 입력하세요.",
    "keyStored": "구성됨, 바꾸려면 새 값 입력",
    "loadFailed": "공급자 목록을 불러오지 못했습니다",
    "maxTokens": "최대 출력 토큰",
    "maxTokensPlaceholder": "공급자 기본값 사용",
    "model": "모델",
    "modelAdvanced": "모델 옵션",
    "modelCapacityInvalid": "용량은 숫자여야 하며, 뒤에 K나 M을 붙일 수 있습니다.",
    "modelContextInvalid": "컨텍스트 창은 131072, 256K, 1M처럼 양수여야 합니다.",
    "modelDuplicate": "모델 ID는 한 번씩만 쓸 수 있습니다.",
    "modelId": "모델 ID",
    "modelIdDuplicate": "모델 ID는 겹치면 안 됩니다.",
    "modelIdRequired": "모델 ID를 입력하세요.",
    "modelInputImage": "이미지",
    "modelInputText": "텍스트",
    "modelInputTypes": "입력 유형",
    "modelMaxTokensInvalid": "최대 출력 토큰은 8192, 64K, 1M처럼 양수여야 합니다.",
    "modelName": "표시 이름",
    "modelNameInvalid": "표시 이름을 비워 둘 수 없습니다.",
    "modelNamePlaceholder": "비워 두면 모델 ID 사용",
    "models": "모델",
    "modelsCustomized": "변경한 모델 목록",
    "modelsEmpty": "선택 목록에 모델이 표시되지 않습니다. 목록에 없는 ID도 직접 보낼 수는 있습니다.",
    "modelsInherited": "어댑터 기본값 사용 중",
    "nav": "모델",
    "onboardingDescription": "공식 DeepSeek 공급자를 구성하고 시작하세요.",
    "onboardingLater": "나중에 구성",
    "onboardingSave": "저장하고 계속",
    "onboardingSaving": "저장하는 중…",
    "onboardingTitle": "시작하려면 API 키를 추가하세요",
    "protocolAnthropicMessages": "Anthropic Messages",
    "protocolOpenAiCompletions": "OpenAI Chat Completions",
    "protocolOpenAiResponses": "OpenAI Responses",
    "provider": "공급자",
    "readOnly": "이 배포 환경에서는 설정 문서가 읽기 전용입니다.",
    "remove": "삭제",
    "removeModel": "모델 삭제",
    "removeProvider": "{provider} 삭제",
    "resetModels": "기본값 복원",
    "retry": "다시 시도",
    "savedProvider": "{provider} 공급자를 저장했습니다.",
    "settingsPathUnresolvable": "설정 경로를 찾을 수 없음",
    "title": "모델",
    "welcomeBody": "DeepSeek Harness 0.2는 아직 프리뷰 단계라 여러 부분을 계속 다듬고 개선해야 합니다. 모든 개발자와 사용자의 피드백과 제안을 환영합니다. 새 데스크톱 앱은 이제 폭넓은 사용자를 대상으로 합니다. 개발자용 고급 기능은 설정에서 켤 수 있습니다. DeepSeek Harness의 제품 기능과 플러그인 API는 앞으로도 빠르게 바뀌다가 차차 안정될 예정입니다.\n\n오픈 소스로 재사용하고 조합할 수 있는 기반 위에서, 전 세계 사용자와 개발자와 함께 지능의 한계를 탐구해 나가고 싶습니다. 누구든 DeepSeek Harness로 아이디어를 실현하고 커뮤니티에 참여해 플러그인 생태계를 함께 넓혀 주시길 바랍니다.",
    "welcomeContinue": "계속",
    "welcomeError": "확인 내용을 저장하지 못했습니다. 다시 시도해 주세요.",
    "welcomeTitle": "프리뷰 안내"
  },
  "settings.permission": {
    "confirm.acknowledge": "위험을 이해했으며 계속하겠습니다",
    "confirm.cancel": "취소",
    "confirm.description": "전체 접근을 켜면 새 세션에서 확인 절차가 줄어 민감한 작업, 파일 변경, 외부 명령 등을 더 많이 바로 실행합니다. 이후 작업을 신뢰할 수 있을 때만 쓰세요.",
    "confirm.enable": "전체 접근 사용",
    "confirm.title": "전체 접근을 사용할까요?",
    "description": "새 세션의 기본 권한 모드를 고릅니다",
    "loading": "불러오는 중",
    "preset.fullAccess": "전체 접근",
    "preset.readOnly": "읽기 전용",
    "preset.workspaceWrite": "워크스페이스 쓰기",
    "title": "권한",
    "unavailable": "사용할 수 없음"
  },
  "settings.pluginInventory": {
    "active": "실행 중",
    "clientSyncFailed": "이 페이지에서 일부 플러그인을 동기화하지 못했습니다. 호스트의 사용 설정은 바뀌지 않았습니다.",
    "clientSyncRetry": "이 페이지 다시 시도",
    "clientSyncing": "이 페이지의 플러그인 동기화 중…",
    "condition": "사용 안 함 조건",
    "conditionalTag": "조건부",
    "configuration": "구성",
    "countUnit": "개",
    "disabledTag": "사용 안 함",
    "empty": "사용할 수 있는 플러그인이 없습니다.",
    "emptySearch": "일치하는 플러그인이 없습니다.",
    "enabledIn": "사용 위치",
    "enabledTag": "사용",
    "error": "지금은 플러그인을 쓸 수 없습니다.",
    "failed": "시작 실패",
    "failedCountLabel": "실패",
    "failedTag": "실패",
    "fromPreset": "출처",
    "globalSubtitle": "시스템과 모든 세션이 함께 씀",
    "globalTitle": "전역 플러그인",
    "loading": "플러그인 읽는 중…",
    "loadingPhase": "불러오는 중",
    "matchesInOtherPresets": "다른 프리셋에서 {count}개 더 일치: ",
    "metadataError": "패키지 메타데이터 오류: {error}",
    "moduleLabel": "모듈",
    "pending": "의존성 기다리는 중",
    "presetEnabledTag": "프리셋에서 사용",
    "presetOptionBroken": "{name} (불러오지 못함)",
    "presetOptionDefault": "{name} (기본값)",
    "presetProvidedDetail": "전역에서는 사용 안 함. 에이전트 프리셋이 세션마다 제공함",
    "presetSubtitle": "에이전트 프리셋이 세션마다 구성함",
    "presetTitle": "세션 플러그인",
    "retry": "다시 시도",
    "runtime": "상태",
    "search": "플러그인 검색",
    "switcherLabel": "살펴볼 에이전트 프리셋 선택",
    "tab": "플러그인 목록",
    "unloading": "언로드 중",
    "unobserved": "실행 중 아님",
    "viewInPreset": "프리셋 그룹에서 보기"
  },
  "settings.plugins": {
    "empty": "이 배포 환경에는 플러그인 화면이 없습니다.",
    "intro": "이 배포 환경에 포함된 플러그인을 살펴봅니다.",
    "nav": "기본 제공 플러그인",
    "tabs": "플러그인 화면",
    "title": "기본 제공 플러그인"
  },
  "settings.sessionLog": {
    "description": "DeepSeek 모델과 제품 개선에 도움이 됩니다.",
    "failed": "설정을 저장하지 못했습니다",
    "saved": "설정을 저장했습니다",
    "title": "공식 모델 API를 쓸 때 세션 로그 업로드"
  },
  "settings.shell": {
    "description": "명령 하나가 실행되는 시간과 출력량을 제한합니다.",
    "invalidNumber": "숫자를 입력하거나, 기본값을 쓰려면 비워 두세요.",
    "maxOutputBytes": "스트림별 출력 한도(바이트)",
    "maxOutputBytesHint": "한도를 넘는 출력은 버리지 않고 임시 파일에 저장합니다.",
    "overridden": "변경됨",
    "readOnly": "이 배포 환경에서는 설정이 읽기 전용입니다.",
    "reset": "기본값으로 되돌리기",
    "save": "저장",
    "saveFailed": "배포 환경에서 이 값을 받아들이지 않았습니다. 고칠 수 있도록 입력한 값은 그대로 두었습니다.",
    "saving": "저장하는 중…",
    "timeoutMs": "명령 제한 시간(ms)",
    "timeoutMsHint": "명령 하나가 강제 종료되기 전까지 실행할 수 있는 시간입니다.",
    "title": "셸",
    "unavailable": "이 플러그인을 불러오지 않아 지금은 설정할 수 없습니다."
  },
  "settings.subagent": {
    "overridden": "변경됨",
    "readOnly": "이 배포 환경에서는 설정이 읽기 전용입니다.",
    "reset": "기본값으로 되돌리기",
    "save": "저장",
    "saveFailed": "배포 환경에서 이 값을 받아들이지 않았습니다. 고칠 수 있도록 입력한 값은 그대로 두었습니다.",
    "saving": "저장하는 중…",
    "subagentCapacityHelp": "같은 메인 에이전트 아래에서 동시에 살아 있는 서브에이전트의 총수입니다. 모든 재귀 단계를 합산하며 메인 에이전트는 빼고 셉니다. 한도에 이르면 새 시작 요청은 거부됩니다.",
    "subagentCapacityHelpLabel": "서브에이전트 동시 실행 한도 안내",
    "subagentCapacityInvalid": "1 이상의 정수를 입력하세요.",
    "subagentDepthHelp": "에이전트가 서브에이전트를 몇 단계까지 만들 수 있는지 제한합니다.",
    "subagentDepthHelpLabel": "최대 재귀 깊이 안내",
    "subagentDepthInvalid": "0 이상의 정수를 입력하세요.",
    "subagentDepthOne": "메인 에이전트만 서브에이전트를 만들 수 있음",
    "subagentDepthOverride": "도구에 자체 최대 재귀 깊이가 정의되어 있으면 그 설정을 우선합니다.",
    "subagentDepthZero": "서브에이전트 사용 안 함",
    "subagentDescription": "서브에이전트의 재귀 깊이, 개수, 모델을 설정합니다.",
    "subagentLimitsTitle": "한도",
    "subagentMaxActive": "서브에이전트 동시 실행 한도",
    "subagentMaxDepth": "최대 재귀 깊이",
    "subagentModelSelectionAllowed": "에이전트가 고를 수 있는 모델",
    "subagentModelSelectionChoose": "켜면 에이전트가 아래 허용된 모델 중에서 서브에이전트마다 공급자, 모델, 추론 강도를 고를 수 있습니다. 새 세션에만 적용됩니다.",
    "subagentModelSelectionConflict": "다른 곳에서 설정이 바뀌었습니다. 작성 중인 내용을 버리고 다시 시도해 주세요.",
    "subagentModelSelectionEmpty": "현재 모델을 제공하는 모델 공급자가 없습니다.",
    "subagentModelSelectionLoadFailed": "모델을 불러오지 못했습니다.",
    "subagentModelSelectionLoading": "모델 불러오는 중…",
    "subagentModelSelectionOff": "서브에이전트는 구성된 기본값을 쓰거나 상위 에이전트의 모델을 이어받습니다. 저장한 모델 선택은 유지됩니다.",
    "subagentModelSelectionPartial": "일부 모델 공급자를 불러오지 못했습니다. 저장한 선택은 지금도 제거할 수 있습니다.",
    "subagentModelSelectionRequired": "저장하려면 모델을 하나 이상 고르세요.",
    "subagentModelSelectionRetry": "다시 시도",
    "subagentModelSelectionTitle": "모델 선택",
    "subagentModelSelectionToggle": "에이전트가 서브에이전트 모델을 고르도록 허용",
    "subagentModelSelectionUnavailable": "지금은 사용할 수 없음",
    "subagentModelSelectionUnavailableGroup": "저장했지만 지금은 사용할 수 없음",
    "subagentTitle": "서브에이전트",
    "unavailable": "이 플러그인을 불러오지 않아 지금은 설정할 수 없습니다."
  },
  "settings.theme": {
    "appearance.dark": "다크",
    "appearance.light": "라이트",
    "appearance.system": "시스템",
    "appearance.title": "화면 모드",
    "fontSize.decrease": "글자 크기 줄이기",
    "fontSize.description": "대화 내용에만 적용됩니다",
    "fontSize.increase": "글자 크기 키우기",
    "fontSize.title": "글자 크기",
    "fontSize.unit": "px"
  },
  "settings.webSearch": {
    "apiKey": "API 키",
    "apiKeyHint": "설정 파일 밖에 저장합니다. 현재 키를 그대로 쓰려면 비워 두세요.",
    "apiKeySet": "키가 구성되어 있습니다.",
    "apiKeyUnset": "구성된 키가 없습니다. DeepSeek 계정 모델을 쓰는 대화만 기본 엔드포인트로 검색할 수 있습니다.",
    "baseUrl": "엔드포인트",
    "baseUrlHint": "공급자 기본값을 쓰려면 비워 두세요.",
    "description": "DeepSeek 검색 공급자를 설정합니다.",
    "invalidNumber": "숫자를 입력하거나, 기본값을 쓰려면 비워 두세요.",
    "maxUses": "요청당 최대 검색 횟수",
    "maxUsesHint": "한 요청이 답하기 전까지 검색할 수 있는 횟수입니다.",
    "overridden": "변경됨",
    "readOnly": "이 배포 환경에서는 설정이 읽기 전용입니다.",
    "reset": "기본값으로 되돌리기",
    "save": "저장",
    "saveFailed": "배포 환경에서 이 값을 받아들이지 않았습니다. 고칠 수 있도록 입력한 값은 그대로 두었습니다.",
    "saving": "저장하는 중…",
    "title": "웹 검색",
    "unavailable": "이 플러그인을 불러오지 않아 지금은 설정할 수 없습니다."
  },
  "shortcuts": {
    "application": "앱",
    "approval": "승인 영역",
    "cancel": "취소",
    "clear": "제거",
    "clear-search": "검색어 지우기",
    "close": "키보드 단축키 닫기",
    "close-confirmation": "확인 창 닫기",
    "conflict": "“{commands}”에서 이미 사용 중",
    "description": "사용할 수 있는 단축키와 입력 동작을 보고 편집합니다",
    "desktop-document": "userData/keybindings.json",
    "desktop-reload": "Harness를 다시 시작하세요",
    "dismiss": "메뉴나 맨 위 대화 상자 닫기",
    "edit-label": "{command} 단축키 편집",
    "empty": "일치하는 단축키가 없습니다",
    "future": "{location}에 있는 단축키 설정은 더 새로운 버전에서 만든 것입니다. Harness를 업그레이드한 뒤 다시 시도해 주세요.",
    "global-hint": "어디서나 열기",
    "input": "메시지 입력",
    "invalid": "{location}에 있는 단축키 설정이 손상되었습니다. 이 설정을 백업하고 고친 다음 {reload}.",
    "macos-web-help": "Command+/, Command+,, Command+Backslash, Control+Backquote, Command+Option+키, Command+Shift+키를 쓸 수 있습니다. 서로 다른 보조 키 3~4개를 함께 쓰는 조합도 지원합니다. 브라우저나 시스템 단축키는 페이지에 전달되지 않을 수 있습니다.",
    "menus": "메뉴와 대화 상자",
    "modified-count": "{count}개 변경함",
    "modifier-required": "조합에 Command, Ctrl, Alt 중 하나를 넣으세요.",
    "move": "메뉴 선택 이동",
    "native-failed": "데스크톱 키 입력 기록을 보호하지 못했습니다. 기록을 끝내고 다시 시도해 주세요.",
    "not-ready": "단축키가 아직 준비되지 않았습니다. 다시 시도해 주세요.",
    "open": "키보드 단축키 열기",
    "read": "{location}에서 단축키 설정을 읽을 수 없습니다. 접근 권한을 확인한 뒤 {reload}.",
    "record": "단축키를 누르세요",
    "record-help": "키를 떼면 저장합니다. Tab으로 동작 사이를 이동하고 Esc로 취소합니다.",
    "reserved": "시스템이나 텍스트 편집 동작용으로 예약된 조합입니다.",
    "reset": "기본값 복원",
    "reset-all": "모두 기본값으로 복원",
    "reset-description": "이 플랫폼의 기본 단축키로 되돌립니다. 바꾸거나 지운 단축키가 모두 원래대로 돌아옵니다. 다른 플랫폼에는 영향이 없습니다.",
    "reset-failed": "기본값으로 복원하지 못했습니다. 단축키는 그대로입니다. 다시 시도해 주세요.",
    "reset-saved": "기본 단축키를 복원했습니다",
    "reset-title": "모든 단축키를 기본값으로 복원할까요?",
    "retry-save": "다시 저장",
    "review": "최신 설정을 확인했습니다",
    "saved": "변경됨",
    "search": "단축키 검색",
    "select": "메뉴 항목 선택",
    "settings": "키보드 단축키",
    "stale": "단축키 설정이나 사용할 수 있는 명령이 바뀌었습니다. 저장하기 전에 최신 바인딩을 확인하세요.",
    "title": "키보드 단축키",
    "too-many-keys": "보조 키가 아닌 키는 두 개까지만 누를 수 있습니다. 키를 뗀 뒤 다시 시도해 주세요.",
    "unbound": "단축키 없음",
    "unsupported-browser": "이 브라우저는 아직 이 조합을 지원하지 않습니다.",
    "unsupported-key": "지원하지 않는 키입니다.",
    "using-accepted": "마지막으로 읽은 바인딩을 계속 씁니다.",
    "using-defaults": "기본 바인딩을 쓰고 있습니다.",
    "view": "단축키 편집",
    "web-document": "이 사이트의 localStorage 항목 dsh.keybindings.v1",
    "web-help": "브라우저 조합: Mod+/, Mod+Shift+,, Mod+Shift+.. Mod는 Mac에서 Command, 그 밖의 환경에서 Ctrl입니다.",
    "web-reload": "페이지를 새로 고치세요",
    "windows-web-help": "Ctrl+/, Ctrl+,, Ctrl+Alt+키, Ctrl+Shift+키를 쓸 수 있습니다. 서로 다른 보조 키 3~4개를 함께 쓰는 조합도 지원합니다. 브라우저나 시스템 단축키는 페이지에 전달되지 않을 수 있습니다.",
    "write-failed": "저장하지 못했습니다. 이전 단축키와 작성 중인 내용은 그대로 있습니다. 다시 시도해 주세요."
  },
  "shortcuts.layout": {
    "toggle": "왼쪽 사이드바 열기/닫기"
  },
  "skill": {
    "menu.userOnly": "사용자 전용",
    "row.failed": "스킬 불러오기 실패",
    "row.inspect": "검사",
    "row.instructions": "지침",
    "row.preparing": "스킬 불러오기 준비 중",
    "row.running": "스킬 불러오는 중",
    "row.stopped": "스킬 불러오기 중지됨",
    "row.title": "스킬"
  },
  "slash.menu": {
    "command": "명령",
    "crumbs.aria": "폴더 탐색",
    "drill.aria": "폴더 보기",
    "drill.hint": "폴더 보기",
    "drill.key": "Tab",
    "loading": "불러오는 중…",
    "skill": "스킬",
    "subagent": "서브에이전트",
    "suggestions.aria": "추천 항목"
  },
  "trajectory": {
    "attachment.imageName": "이미지 {index}",
    "attachment.list": "첨부 파일",
    "block.label": "블록 #{index} {type}",
    "block.openSummary": "블록 #{index} 도구 호출 요약 열기",
    "block.openSummaryTitle": "도구 호출 요약 열기",
    "code.copyOutput": "출력 복사",
    "code.copySource": "코드 복사",
    "code.originalJson": "원본 JSON",
    "code.output": "출력",
    "code.running": "실행 중…",
    "code.source": "코드",
    "column.input": "입력",
    "column.model": "모델",
    "column.output": "출력",
    "column.think": "생각",
    "column.time": "시간",
    "column.tools": "도구",
    "details.assistantMessage": "어시스턴트 메시지",
    "details.close": "세부 정보 닫기",
    "details.compacted": "압축됨",
    "details.error": "오류",
    "details.event": "이벤트 세부 정보",
    "details.failure.auth": "API 키가 올바르지 않습니다",
    "details.hierarchy": "계층",
    "details.model": "모델",
    "details.provider": "공급자",
    "details.purpose": "용도",
    "details.resize": "이벤트 세부 정보 크기 조절",
    "details.resizeTitle": "끌어서 크기를 조절합니다. 두 번 클릭하면 원래대로 돌아갑니다.",
    "details.result": "결과",
    "details.retry": "재시도",
    "details.retryDelay": "재시도 대기 시간",
    "details.scheduled": "예약됨",
    "details.source": "출처",
    "details.status": "상태",
    "details.subtoolCalls": "하위 도구 호출",
    "details.toolCall": "도구 호출",
    "details.toolCalls": "도구 호출",
    "group.compaction": "압축 {seq}",
    "group.message": "메시지",
    "group.step": "단계 {step}",
    "history.clickToLoadEarlier": "클릭해 이전 기록 불러오기",
    "history.loadEarlier": "이전 기록 불러오기",
    "history.loadingEarlier": "이전 기록 불러오는 중…",
    "history.loadingEarlierAria": "이전 기록 불러오는 중…",
    "history.loadingTrajectory": "실행 기록 불러오는 중…",
    "kind.assistant": "어시스턴트",
    "kind.compacted": "압축됨",
    "kind.context": "컨텍스트",
    "kind.message": "메시지",
    "kind.sub": "하위",
    "kind.subtool": "하위 도구",
    "kind.system": "시스템",
    "kind.tool": "도구",
    "kind.user": "사용자",
    "layout.compacted": "컨텍스트 압축됨",
    "layout.compacting": "컨텍스트 압축 중…",
    "layout.compactionFailed": "압축 실패",
    "layout.compactionInterrupted": "압축이 끝나기 전에 중단되었습니다.",
    "layout.fileAttachments": "파일 ×{count}",
    "layout.imageCount": "이미지 ×{count}",
    "layout.initialSystemPrompt": "초기 시스템 프롬프트",
    "layout.systemPromptAndToolsUpdated": "시스템 프롬프트와 도구 업데이트됨",
    "layout.systemPromptUpdated": "시스템 프롬프트 업데이트됨",
    "layout.toolAdded": "도구 추가됨: {name}",
    "layout.toolCallOnly": "도구 호출만",
    "layout.toolRemoved": "도구 제거됨: {name}",
    "layout.toolUpdateNotice": "도구 업데이트됨",
    "layout.toolsAdded": "추가됨: {names}",
    "layout.toolsAddedCount": "{count}개 추가됨",
    "layout.toolsChanged": "{added}개 추가, {removed}개 제거",
    "layout.toolsRemoved": "제거됨: {names}",
    "layout.toolsRemovedCount": "{count}개 제거됨",
    "layout.toolsUpdated": "도구 업데이트됨",
    "options.json": "요청 옵션 JSON",
    "options.notRecorded": "옵션이 기록되지 않음",
    "record.json": "JSON",
    "record.namedParametersJson": "{name} 매개변수 JSON",
    "record.noContent": "내용 없음",
    "record.noOutput": "출력 없음",
    "record.noPayload": "기록된 페이로드 없음",
    "record.noResult": "기록된 결과 없음",
    "record.outputJson": "결과 JSON",
    "record.parameters": "매개변수",
    "record.parametersJson": "매개변수 JSON",
    "record.payloadJson": "페이로드 JSON",
    "record.resultJson": "결과 JSON",
    "record.schemaUnavailable": "스키마 없음",
    "record.systemPrompt": "시스템 프롬프트",
    "record.systemPromptMissing": "이 요청에는 시스템 프롬프트가 없습니다",
    "record.thinking": "생각",
    "record.toolCallOnly": "(도구 호출만)",
    "record.tools": "도구",
    "record.toolsMissing": "이 요청에는 도구가 없습니다",
    "record.wrapLines": "줄 바꿈",
    "request.collapsedAssistant": "어시스턴트",
    "request.collapsedSummary": "접힌 {kind} 요약, {summary}",
    "request.collapsedTurn": "턴",
    "request.compaction": "압축 · {section}",
    "request.compactionPurpose": "압축",
    "request.label": "요청 #{request}",
    "request.labelCompaction": "요청 #{request} · 압축",
    "request.noContent": "내용 없음",
    "request.retryProgress": "{retry}/{maximum}",
    "request.rowAria": "{request}{kind}, {content}",
    "request.rowAriaCompaction": "요청 {request}, 압축",
    "request.rowPrefix": "요청 {request}, ",
    "section.betweenTurns": "턴 사이",
    "source.goal": "목표",
    "source.goalRound": "목표 · {round}회차",
    "source.messageJson": "메시지 원본 JSON",
    "source.notRecorded": "출처가 기록되지 않음",
    "source.plugin": "플러그인",
    "source.pluginNamed": "플러그인 · {plugin}",
    "source.unknown": "알 수 없음",
    "source.user": "사용자",
    "status.completed": "완료",
    "status.failed": "실패",
    "status.pending": "대기 중",
    "summary.steps.one": "단계 {count}개",
    "summary.steps.other": "단계 {count}개",
    "summary.toolCalls.one": "도구 호출 {count}회",
    "summary.toolCalls.other": "도구 호출 {count}회",
    "tab.diff": "변경 사항",
    "tab.options": "옵션",
    "tab.payload": "페이로드",
    "tab.preview": "미리보기",
    "tab.raw": "원본",
    "tab.rawOutput": "원본 출력",
    "tab.result": "결과",
    "tab.schema": "스키마",
    "tab.source": "출처",
    "tab.summary": "요약",
    "tab.systemPrompt": "시스템 프롬프트",
    "tab.timing": "시간",
    "tab.tools": "도구",
    "tab.usage": "사용량",
    "timeline.aria": "실행 기록 타임라인",
    "timeline.noTimingData": "시간 데이터 없음",
    "timeline.overviewAria": "타임라인 개요, 가로로 끌어서 이벤트 구간을 확대합니다",
    "timeline.started": "시작 {time}",
    "timeline.total": "합계 {duration}",
    "timeline.ttftDecoding": "TTFT {ttft} · 디코딩 {decoding}",
    "timing.duration": "소요 시간",
    "timing.durationTooShort": "소요 시간이 너무 짧음",
    "timing.firstTokenUnavailable": "첫 토큰 정보 없음",
    "timing.generation": "생성",
    "timing.notAvailable": "정보 없음",
    "timing.notRecorded": "기록되지 않음",
    "timing.outputTokensUnavailable": "출력 토큰 정보 없음",
    "timing.request": "요청 시간",
    "timing.sessionTimestamps": "세션 타임스탬프",
    "timing.sessionTimestampsRunning": "세션 타임스탬프(실행 중)",
    "timing.showLocalTime": "현지 시각 표시",
    "timing.showUnixTimestamp": "Unix 타임스탬프 표시",
    "timing.source": "시간 출처",
    "timing.started": "시작",
    "timing.stepStartUnavailable": "단계 시작 정보 없음",
    "timing.throughput": "처리량",
    "timing.totalDuration": "전체 소요 시간",
    "timing.ttft": "TTFT",
    "timing.usageUnavailable": "사용량 정보 없음",
    "toolbar.actualTime": "실제 시간",
    "toolbar.aria": "실행 기록 도구 모음",
    "toolbar.calls": "호출",
    "toolbar.collapseCalls": "호출 접기",
    "toolbar.collapseTurns": "턴 접기",
    "toolbar.duration": "소요 시간",
    "toolbar.expandCalls": "호출 펼치기",
    "toolbar.expandTurns": "턴 펼치기",
    "toolbar.search": "실행 기록 검색",
    "toolbar.searchPlaceholder": "검색",
    "toolbar.turns": "턴",
    "toolbar.useActualDuration": "실제 소요 시간으로 표시",
    "toolbar.useEqualWidth": "작업을 같은 너비로 표시",
    "turn.label": "턴 {turn}",
    "unit.milliseconds": "{value} ms",
    "unit.seconds": "{value}초",
    "unit.tokens": "{value} tok",
    "unit.tokensPerSecond": "{value} tok/s",
    "usage.cacheCreated": "캐시 생성",
    "usage.cached": "캐시됨",
    "usage.content": "콘텐츠",
    "usage.input": "입력",
    "usage.notReported": "사용량이 보고되지 않음",
    "usage.other": "기타",
    "usage.output": "출력",
    "usage.reasoning": "추론",
    "usage.sessionCumulative": "세션 누적",
    "usage.thisRequest": "이번 요청",
    "usage.tokens": "토큰",
    "view.trajectory": "실행 기록"
  }
}

window.__ModuleLoader__.load({
  id: 'dsh-locale-ko',
  factory: () => ({
    inject: ['locale'],
    apply(ctx) {
      ctx.effect(() => ctx.locale.addLanguage({ id: 'ko', label: '한국어', fallback: 'en' }), 'dsh-locale-ko: language')
      for (const [ns, dict] of Object.entries(dictionaries)) {
        ctx.effect(() => ctx.locale.register(ns, 'ko', dict), `dsh-locale-ko: ${ns}`)
      }
    },
  }),
})
