/** Korean dictionaries per namespace: { "<namespace>": { "<key>": "<Korean text>" } }. */
const dictionaries = {
  "approval": {
    "allowOnce": "이번만 허용",
    "detail.aria": "승인 세부 정보",
    "escalation": "{toolName} 도구가 권한 상승 실행을 요청합니다",
    "reject": "거부",
    "waiting": "승인 대기 중"
  },
  "chat": {
    "chat.deepDiving": "깊이 탐색 중",
    "chat.deepDivingFor": "{duration}째 깊이 탐색 중 ···",
    "chat.loadError": "기록을 불러오지 못했습니다: {message} ({code})",
    "chat.loadOlder": "이전 기록 불러오기",
    "chat.loadingHistory": "기록 불러오는 중…",
    "chat.toBottom": "맨 아래로",
    "chat.turnNavigation.jump": "{turn}번째 턴으로 이동",
    "chat.turnNavigation.jumpLoad": "불러온 뒤 {turn}번째 턴으로 이동",
    "chat.turnNavigation.label": "턴 탐색",
    "chat.turnNavigation.turn": "턴 {turn}",
    "clock.md": "{m}/{d}",
    "clock.ymd": "{y}-{m}-{d}",
    "command.done": "완료",
    "command.failed": "명령 실패",
    "command.running": "실행 중…",
    "command.title": "명령",
    "duration.compactMinutes": "{minutes}분 {seconds}초",
    "duration.compactSeconds": "{seconds}초",
    "duration.hourUnit": "시간 ",
    "duration.milliseconds": "{milliseconds}ms",
    "duration.minuteUnit": "분 ",
    "duration.secondUnit": "초",
    "fileOpen.title": "파일을 열 수 없음",
    "fileOpen.unknown": "이 파일을 열 수 없습니다",
    "image.close": "이미지 미리보기 닫기",
    "image.dialog": "이미지 미리보기",
    "image.failed": "이미지 미리보기를 쓸 수 없음",
    "image.loading": "이미지 불러오는 중…",
    "image.open": "원본 크기로 보기",
    "json.truncated": "… 잘림, 전체 {total}자",
    "message.accountStopped": "작업 중지됨",
    "message.branch": "새 대화로 분기",
    "message.branchUnavailable": "완료된 턴의 마지막 메시지에서만 쓸 수 있습니다",
    "message.compaction": "컨텍스트 압축됨",
    "message.compaction.commandTitle": "compact",
    "message.compaction.completed": "기록 항목 {items}개를 압축함(약 {tokens}토큰)",
    "message.compaction.expand": "압축 요약 보기",
    "message.compaction.running": "컨텍스트 압축 중…",
    "message.compaction.unavailable": "압축 요약을 볼 수 없음",
    "message.context.catalog.more": "… {count}개 더 있음",
    "message.context.catalog.replaced": "교체된 목록",
    "message.context.instructions.added": "추가됨",
    "message.context.instructions.loaded": "불러옴",
    "message.context.instructions.removed": "제거됨",
    "message.context.instructions.updated": "업데이트됨",
    "message.context.recall.counts": "{retained}개 유지 · {omitted}개 생략",
    "message.context.recall.truncated": "잘림",
    "message.context.relay.from": "세션 {session}에서 전달",
    "message.context.snapshot.supersedes": "이전 스냅숏을 대체함",
    "message.contextInjection": "컨텍스트 주입",
    "message.contextRecall": "세션 기록 불러옴",
    "message.extraBlock": "추가 콘텐츠 블록",
    "message.failure.accountSignInRequired": "DeepSeek에 로그인한 뒤 요청을 받는 곳이 계정 인증을 지원하는지 확인해 주세요.",
    "message.failure.accountSignedOut": "DeepSeek에서 로그아웃해 중지되었습니다.",
    "message.failure.auth": "API 키가 올바르지 않습니다",
    "message.failure.quota": "요청 한도를 모두 썼습니다.",
    "message.maxTokens": "출력 토큰 한도에 도달함",
    "message.maxTokens.hint": "응답이 중간에 끊겼습니다. 앞선 출력은 대화에 남아 있습니다. \"계속\"이라고 보내면 모델이 이어서 답합니다.",
    "message.referenceSeparator": ", ",
    "message.referenceSummary": "참조한 세션 · {labels}",
    "message.retry.active": "모델 요청 다시 시도 중",
    "message.retry.cancelled": "모델 요청 재시도 취소됨",
    "message.retry.delay": "재시도 대기 시간: ",
    "message.retry.failure": "실패 원인: ",
    "message.retry.scheduled": "모델 요청 재시도 대기 중",
    "message.retry.started": "모델 요청을 다시 시도함",
    "message.retry.status": "{label} ({retry}/{maximum}) · {seconds}초",
    "message.stepProcess.code": "코드 실행 중",
    "message.stepProcess.comma": ", ",
    "message.stepProcess.commands": "명령 실행 중",
    "message.stepProcess.done.code": "코드 실행함",
    "message.stepProcess.done.commands": "명령 실행함",
    "message.stepProcess.done.edit": "파일 수정함",
    "message.stepProcess.done.plan": "계획 업데이트함",
    "message.stepProcess.done.questions": "질문함",
    "message.stepProcess.done.read": "파일 읽음",
    "message.stepProcess.done.readImage": "이미지 읽음",
    "message.stepProcess.done.search": "코드 검색함",
    "message.stepProcess.done.subagents": "서브에이전트 조율함",
    "message.stepProcess.done.thinking": "분석 완료",
    "message.stepProcess.done.tools": "도구 호출함",
    "message.stepProcess.done.webFetch": "웹 페이지 방문함",
    "message.stepProcess.done.webSearch": "웹 검색함",
    "message.stepProcess.done.write": "파일 작성함",
    "message.stepProcess.edit": "파일 수정 중",
    "message.stepProcess.joinTwo": "{first}, {second}",
    "message.stepProcess.more": "{title} 등",
    "message.stepProcess.plan": "계획 업데이트 중",
    "message.stepProcess.prepare.code": "코드 실행 준비 중",
    "message.stepProcess.prepare.commands": "명령 실행 준비 중",
    "message.stepProcess.prepare.edit": "파일 수정 준비 중",
    "message.stepProcess.prepare.plan": "계획 업데이트 준비 중",
    "message.stepProcess.prepare.questions": "질문 준비 중",
    "message.stepProcess.prepare.read": "파일 읽기 준비 중",
    "message.stepProcess.prepare.readImage": "이미지 읽기 준비 중",
    "message.stepProcess.prepare.search": "코드 검색 준비 중",
    "message.stepProcess.prepare.subagents": "서브에이전트 조율 준비 중",
    "message.stepProcess.prepare.tools": "도구 호출 준비 중",
    "message.stepProcess.prepare.webFetch": "웹 페이지 방문 준비 중",
    "message.stepProcess.prepare.webSearch": "웹 검색 준비 중",
    "message.stepProcess.prepare.write": "파일 작성 준비 중",
    "message.stepProcess.questions": "응답 기다리는 중",
    "message.stepProcess.read": "파일 읽는 중",
    "message.stepProcess.readImage": "이미지 읽는 중",
    "message.stepProcess.search": "코드 검색 중",
    "message.stepProcess.sharedPrefix": "",
    "message.stepProcess.subagents": "서브에이전트 조율 중",
    "message.stepProcess.thinking": "요청 분석 중",
    "message.stepProcess.tools": "도구 호출 중",
    "message.stepProcess.webFetch": "웹 페이지 방문 중",
    "message.stepProcess.webSearch": "웹 검색 중",
    "message.stepProcess.write": "파일 작성 중",
    "message.stopped": "중지됨",
    "message.systemPrompt": "시스템 프롬프트",
    "message.systemPromptUpdate": "시스템 프롬프트 업데이트",
    "message.think": "생각",
    "message.tokensPerSecond": "{tps} tok/s",
    "message.toolAdded": "도구 추가됨: {name}",
    "message.toolRemoved": "도구 제거됨: {name}",
    "message.toolsAdded": "추가됨: {names}",
    "message.toolsAddedCount": "{count}개 추가됨",
    "message.toolsChanged": "{added}개 추가, {removed}개 제거",
    "message.toolsRemoved": "제거됨: {names}",
    "message.toolsRemovedCount": "{count}개 제거됨",
    "message.toolsUpdated": "도구 업데이트됨",
    "message.trigger.agent": "작업 메시지 받음",
    "message.trigger.explanation": "이 알림을 받고 응답을 시작했습니다.",
    "message.trigger.github": "GitHub 이벤트 받음",
    "message.trigger.goal": "목표 이어서 진행",
    "message.trigger.job": "백그라운드 작업 업데이트됨",
    "message.trigger.plugin": "플러그인 상태 업데이트됨",
    "message.trigger.request": "실행 요청됨",
    "message.trigger.schedule": "자동화 작업",
    "message.trigger.subagent": "하위 작업 상태 업데이트됨",
    "message.trigger.team": "팀 메시지 받음",
    "message.trigger.webhook": "외부 이벤트 받음",
    "message.turnError": "이 턴이 실패했습니다",
    "message.turnProcess.failed": "실패",
    "message.turnProcess.messages.one": "메시지 {count}개",
    "message.turnProcess.messages.other": "메시지 {count}개",
    "message.turnProcess.separator": " · ",
    "message.turnProcess.subagents.one": "서브에이전트 {count}개",
    "message.turnProcess.subagents.other": "서브에이전트 {count}개",
    "message.turnProcess.thoughtForAWhile": "잠시 생각함",
    "message.turnProcess.took": "소요 시간 ",
    "message.turnProcess.toolCalls.one": "도구 호출 {count}회",
    "message.turnProcess.toolCalls.other": "도구 호출 {count}회",
    "message.turnProcess.worked": "완료",
    "message.turnUsage.cacheHit": "캐시 적중",
    "message.turnUsage.cacheRead": "캐시된 입력",
    "message.turnUsage.cacheWrite": "캐시 쓰기",
    "message.turnUsage.consumed": "사용량 {total}",
    "message.turnUsage.count": "{count} tok",
    "message.turnUsage.input": "캐시되지 않은 입력",
    "message.turnUsage.model": "공급자 / 모델",
    "message.turnUsage.output": "출력",
    "message.turnUsage.reasoning": " (추론 {tokens})",
    "message.turnUsage.title": "턴 사용량",
    "message.unknownBlock": "알 수 없는 콘텐츠 블록",
    "message.unknownSurface": "알 수 없는 화면 이벤트: {type}",
    "number.groupSeparator": ",",
    "row.failed": "실패",
    "row.running": "실행 중",
    "settings.links.description": "웹 링크를 어디서 열지 고릅니다",
    "settings.links.newTab": "기본 브라우저",
    "settings.links.sidebar": "앱 안 사이드바",
    "settings.links.title": "채팅 링크 열기 위치",
    "settings.performance.compact": "간단히",
    "settings.performance.description": "성능과 사용량 정보를 얼마나 보여 줄지 고릅니다",
    "settings.performance.detailed": "자세히",
    "settings.performance.title": "성능 및 사용량",
    "settings.transcript.compact": "간단히",
    "settings.transcript.description": "도구 호출을 얼마나 자세히 보여 줄지 고릅니다",
    "settings.transcript.detailed": "자세히",
    "settings.transcript.standard": "보통",
    "settings.transcript.title": "작업 과정 표시",
    "settings.transcript.verbose": "모두 표시",
    "stats.cacheHit": "캐시 적중 {percent}%",
    "stats.counts": "턴 {turns}개, 단계 {steps}개",
    "stats.dialog.llmTime": "LLM 시간",
    "stats.dialog.speed": "초당 토큰 수(TPS)",
    "stats.dialog.title": "세션 통계",
    "stats.dialog.toolTime": "도구 시간",
    "stats.dialog.ttft": "첫 토큰까지 평균 시간(TTFT)",
    "stats.dialog.usageTitle": "토큰 사용량",
    "view.chat": "채팅"
  },
  "command": {
    "description.compact": "오래된 대화 기록 압축",
    "description.export": "이 세션 로그를 ZIP 파일로 내려받기",
    "description.feedback": "이 세션에 대한 피드백 남기기",
    "description.goal": "오래 걸리는 작업의 목표 설정 또는 보기",
    "description.permission": "권한 프리셋 전환(샌드박스 모드 + 승인 정책)",
    "description.plan": "계획 모드 시작 또는 종료",
    "label.compact": "압축",
    "label.export": "내보내기",
    "label.feedback": "피드백",
    "label.goal": "목표",
    "label.permission": "권한",
    "label.plan": "계획",
    "listbox.aria": "/{command} 검색 결과",
    "notice.attachmentsUnsupported": "/{command} 명령에는 첨부 파일을 쓸 수 없습니다. 먼저 첨부 파일을 빼 주세요",
    "overlay.aria": "/{command} 옵션",
    "search.aria": "옵션 필터",
    "search.placeholder": "검색…",
    "section.add": "추가",
    "section.commands": "명령",
    "status.applying": "적용하는 중…",
    "status.empty": "옵션 없음",
    "status.loading": "옵션 불러오는 중…",
    "token.compact": "compact",
    "token.export": "export",
    "token.feedback": "feedback",
    "token.goal": "goal",
    "token.permission": "permission",
    "token.plan": "plan"
  },
  "common": {
    "back": "뒤로",
    "brand.localBuild": "DSH 로컬 빌드",
    "cancel": "취소",
    "close": "닫기",
    "codeBlock.title": "코드 블록",
    "codeBlock.unwrap": "줄 바꿈 안 함",
    "codeBlock.wrap": "줄 바꿈",
    "collapse": "접기",
    "copied": "복사됨",
    "copy": "복사",
    "copy.compactJson": "한 줄 JSON 복사",
    "copy.failed": "복사 실패",
    "copy.json": "JSON 복사",
    "copy.optionsHint": "{action}, 오른쪽 클릭하면 복사 옵션",
    "copy.path": "속성 경로 복사",
    "copy.prettyJson": "정렬된 JSON 복사",
    "copy.value": "값 복사",
    "delete": "삭제",
    "edit": "편집",
    "expand": "펼치기",
    "json.label": "JSON",
    "load.failed": "불러오지 못함",
    "loading": "불러오는 중…",
    "markdown.footnotes": "각주",
    "markdown.truncatedCharacters": "… {total}자에서 잘림",
    "more": "더 보기",
    "next": "다음",
    "none": "없음",
    "number.million": "{value}M",
    "number.thousand": "{value}K",
    "ok": "확인",
    "previous": "이전",
    "retry": "다시 시도",
    "save": "저장",
    "search": "검색",
    "skip": "건너뛰기",
    "submit": "제출",
    "submitting": "제출하는 중…",
    "truncated": "잘림",
    "unknown": "알 수 없음",
    "workspace.defaultName": "기본 워크스페이스"
  },
  "conversation": {
    "ask.answered": "{answered}/{total} 답변함",
    "ask.cancelled": "취소됨",
    "ask.cancelledDetail": "답변을 제출하기 전에 질문이 취소되었습니다.",
    "ask.closed": "닫힘",
    "ask.closedDetail": "닫힌 질문입니다. 결과는 아래 대화에 있습니다.",
    "ask.interrupted": "중단됨",
    "ask.interruptedDetail": "답변을 제출하기 전에 질문이 중단되었습니다.",
    "ask.pending": "작업은 계속됨, 아직 답변 가능",
    "ask.pendingDetail": "대기 중인 질문에는 입력창에서 계속 답할 수 있습니다.",
    "ask.reopen": "답변하기",
    "ask.review": "답변 보기",
    "ask.rowTitle": "질문",
    "ask.skipped": "답변하지 않음",
    "ask.waiting": "대기 중",
    "attachment.directoryDesktopOnly": "폴더는 데스크톱 앱에서만 추가할 수 있습니다. 브라우저에서는 파일을 하나씩 추가해 주세요",
    "attachment.dropBlocked": "지금은 파일과 이미지를 추가할 수 없습니다",
    "attachment.dropDesc": "이미지는 최대 {count}개, 개당 {size}까지",
    "attachment.dropTitle": "파일이나 이미지를 여기로 끌어다 놓으세요",
    "attachment.pathUnavailable": "폴더 경로를 가져오지 못했습니다. 다시 끌어다 놓아 주세요",
    "attachment.pathUnsupported": "경로에 참조로 담을 수 없는 문자가 있습니다. 이름을 바꾼 뒤 다시 시도해 주세요",
    "attachment.pending": "대기 중인 첨부 파일",
    "attachment.scrollLeft": "첨부 파일 왼쪽으로 스크롤",
    "attachment.scrollRight": "첨부 파일 오른쪽으로 스크롤",
    "bash.failed": "실패",
    "bash.running": "실행 중",
    "bash.stopped": "중지됨",
    "command.attachmentsUnsupported": "/{command} 명령에는 첨부 파일을 쓸 수 없습니다. 먼저 첨부 파일을 빼 주세요",
    "context.aria": "컨텍스트 {percent} 사용됨",
    "context.messages": "메시지",
    "context.system": "시스템 프롬프트",
    "context.tools": "도구 정의",
    "context.used": "컨텍스트 사용량",
    "detail.agent.reply": "에이전트 응답",
    "detail.agents.count": "에이전트 {count}개",
    "detail.days": "{count}일",
    "detail.empty": "결과 없음",
    "detail.event.neighbors": "주변 이벤트",
    "detail.field.agent": "에이전트 ID",
    "detail.field.agents": "시작한 에이전트",
    "detail.field.availability": "사용 가능 여부",
    "detail.field.bestMatch": "가장 비슷한 항목",
    "detail.field.callId": "호출 ID",
    "detail.field.content": "내용",
    "detail.field.context": "컨텍스트",
    "detail.field.currentPackage": "현재 패키지",
    "detail.field.data": "데이터",
    "detail.field.dependencies": "의존성",
    "detail.field.depth": "깊이",
    "detail.field.diagnostics": "진단",
    "detail.field.exitCode": "종료 코드",
    "detail.field.id": "ID",
    "detail.field.inputSchema": "입력 스키마",
    "detail.field.job": "작업 ID",
    "detail.field.latestRun": "최근 실행",
    "detail.field.message": "메시지",
    "detail.field.messageId": "메시지 ID",
    "detail.field.methods": "메서드",
    "detail.field.model": "모델",
    "detail.field.nextPackage": "다음 패키지",
    "detail.field.outputSchema": "출력 스키마",
    "detail.field.owner": "소유자",
    "detail.field.packages": "패키지",
    "detail.field.parent": "상위",
    "detail.field.pid": "프로세스 ID",
    "detail.field.platform": "플랫폼",
    "detail.field.previousStatus": "이전 상태",
    "detail.field.processGroup": "프로세스 그룹",
    "detail.field.props": "속성",
    "detail.field.provider": "공급자",
    "detail.field.ready": "준비됨",
    "detail.field.registrations": "등록 항목",
    "detail.field.result": "결과",
    "detail.field.revision": "리비전",
    "detail.field.role": "역할",
    "detail.field.root": "루트",
    "detail.field.seq": "이벤트 순번",
    "detail.field.signal": "시그널",
    "detail.field.source": "출처",
    "detail.field.step": "단계",
    "detail.field.surface": "기록 상태",
    "detail.field.target": "대상 이벤트",
    "detail.field.task": "작업",
    "detail.field.time": "시간",
    "detail.field.turn": "턴",
    "detail.field.type": "유형",
    "detail.field.warnings": "경고",
    "detail.field.writeScopes": "쓰기 범위",
    "detail.goal.active": "진행 중",
    "detail.goal.blocked": "막힘",
    "detail.goal.complete": "완료",
    "detail.goal.disarmed": "계속 진행 대기 중",
    "detail.goal.empty": "목표 없음",
    "detail.goal.paused": "일시 중지됨",
    "detail.goal.reason": "막힌 이유",
    "detail.goal.rounds": "회차",
    "detail.hours": "{count}시간",
    "detail.jobs.count": "백그라운드 작업 {count}개",
    "detail.location": "{line}행 {column}열",
    "detail.locations.count": "위치 {count}곳",
    "detail.matches.capped": "결과 한도에 도달했습니다. 더 보려면 검색 범위를 좁혀 주세요",
    "detail.matches.count": "일치 항목 {count}개",
    "detail.minutes": "{count}분",
    "detail.models.title": "사용 가능한 모델",
    "detail.moreInInspect": "검사에서 항목 {count}개를 더 볼 수 있습니다",
    "detail.no": "아니요",
    "detail.none": "없음",
    "detail.output.lines": "전체 {total}줄 중 {begin}–{end}줄",
    "detail.output.truncated": "출력 잘림",
    "detail.plugins.count": "동적 플러그인 {count}개",
    "detail.providers.count": "검사 공급자 {count}개",
    "detail.ralph.limit": "회차 한도에 도달함",
    "detail.ralph.reportedBlocker": "작업자가 막힌 문제를 보고함",
    "detail.ralph.reportedComplete": "작업자가 완료를 보고함",
    "detail.receipt.alreadyFinished": "이미 끝남",
    "detail.receipt.cancel": "취소 요청됨",
    "detail.receipt.closed": "닫힘",
    "detail.receipt.closing": "닫는 중",
    "detail.receipt.delivered": "메시지 전달됨",
    "detail.receipt.interrupt": "중단 요청됨",
    "detail.receipt.signal": "시그널 전달됨",
    "detail.receipt.started": "시작됨",
    "detail.recordedResult": "기록된 결과",
    "detail.report.nextSteps": "남은 작업",
    "detail.schedule.count": "알림 {count}개",
    "detail.schedule.cron": "Cron {expression} ({zone})",
    "detail.schedule.daily": "매일 {time} ({zone})",
    "detail.schedule.deleted": "삭제됨",
    "detail.schedule.empty": "알림 없음",
    "detail.schedule.every": "{interval}마다",
    "detail.schedule.frequency": "반복",
    "detail.schedule.once": "한 번",
    "detail.schedule.overdue": "시간 지남, 세션 재개 대기 중",
    "detail.schedule.scheduled": "예약됨",
    "detail.schedule.weekly": "매주 {days}요일 {time} ({zone})",
    "detail.schedule.when": "예약 시각",
    "detail.seconds": "{count}초",
    "detail.state": "상태",
    "detail.status.accepted": "수락됨",
    "detail.status.completed": "완료",
    "detail.status.deleted": "삭제됨",
    "detail.status.exited": "종료됨",
    "detail.status.failed": "실패",
    "detail.status.idle": "유휴",
    "detail.status.inactive": "비활성",
    "detail.status.killed": "취소됨",
    "detail.status.provisioning": "준비 중",
    "detail.status.queued": "대기 중",
    "detail.status.ready": "준비됨",
    "detail.status.running": "실행 중",
    "detail.tasks.count": "팀 작업 {count}개",
    "detail.tasks.nextPage": "작업이 더 있습니다. 다음 커서는 {cursor}입니다",
    "detail.terminals.count": "터미널 {count}개",
    "detail.todo.completed": "완료",
    "detail.todo.empty": "할 일 목록이 비어 있습니다",
    "detail.todo.in_progress": "진행 중",
    "detail.todo.pending": "대기 중",
    "detail.trace.ancestors": "상위 세션",
    "detail.trace.derived": "파생 이벤트",
    "detail.trace.descendants": "하위 세션",
    "detail.trace.replacedBy": "대체한 항목",
    "detail.trace.replacementChain": "대체 체인",
    "detail.trace.replaces": "대체된 이벤트",
    "detail.trace.sources": "원본 이벤트",
    "detail.wait.changed": "변경 감지됨",
    "detail.wait.noProgress": "실행 중인 서브에이전트 없음",
    "detail.wait.timeout": "대기 시간 초과",
    "detail.wait.title": "서브에이전트 활동",
    "detail.weekday.1": "월",
    "detail.weekday.2": "화",
    "detail.weekday.3": "수",
    "detail.weekday.4": "목",
    "detail.weekday.5": "금",
    "detail.weekday.6": "토",
    "detail.weekday.7": "일",
    "detail.weekday.join": ", ",
    "detail.workflow.script": "워크플로 스크립트",
    "detail.yes": "예",
    "details.running": "실행 중…",
    "diff.collapseAria": "변경 사항 접기",
    "diff.expandAria": "변경 줄 {count}개 더 펼치기",
    "diff.expandRest": "… {count}줄 더 있음",
    "error.sessionInUse": "이 세션은 이미 사용 중입니다. 실행 중인 다른 DSH 인스턴스(dsh web이나 데스크톱 앱 등)가 쓰고 있을 수 있습니다. 다른 DSH 인스턴스를 종료하고 다시 시도해 주세요.",
    "file.label": "파일",
    "file.notStaged": "파일 업로드가 끝나지 않았습니다. 다시 추가한 뒤 시도해 주세요",
    "file.pending": "대기 중인 파일",
    "file.remove": "{name} 파일 제거",
    "file.retry": "{name} 파일 다시 업로드",
    "file.sessionUnavailable": "세션을 쓸 수 없어 파일을 업로드할 수 없습니다",
    "file.stillUploading": "파일을 아직 업로드하고 있습니다. 끝난 뒤에 보내 주세요",
    "file.uploadFailed": "업로드 실패, 클릭해 다시 시도",
    "file.uploading": "업로드하는 중…",
    "hero.chooseWorkspace": "워크스페이스 선택",
    "hero.headline": "미지의 세계로",
    "hero.preview": "프리뷰",
    "hint.goal": "오래 걸리는 작업의 목표를 적어 주세요",
    "hint.goal.active": "목표 진행 중: edit / pause / resume / clear",
    "hint.plan": "작업을 설명하면 계획을 세웁니다",
    "image.closePreview": "원본 이미지 미리보기 닫기",
    "image.dimensionTooLarge": "이미지 가로세로는 각각 {size}px 이하여야 합니다. 크기를 줄여 다시 시도해 주세요",
    "image.fileTooLarge": "이미지는 한 장당 {size}보다 작아야 합니다",
    "image.label": "이미지",
    "image.loadFailed": "이미지를 불러오지 못했습니다. 클릭해 다시 시도해 주세요",
    "image.loading": "이미지 불러오는 중…",
    "image.modelUnsupported": "현재 모델은 이미지를 지원하지 않습니다. 이미지를 지원하는 모델로 바꿔 주세요",
    "image.openOriginal": "원본 보기",
    "image.openOriginalLabel": "{label}, 클릭해 원본 보기",
    "image.original": "원본 이미지",
    "image.pending": "대기 중인 이미지",
    "image.preview": "원본 이미지 미리보기",
    "image.remove": "{name} 이미지 제거",
    "image.sendFailed": "이미지를 보내지 못했습니다({reason}). 다시 추가한 뒤 시도해 주세요",
    "image.tooMany": "메시지 하나에 이미지는 최대 {count}개까지 넣을 수 있습니다",
    "image.tooManyPixels": "이미지 해상도가 너무 높습니다. 압축한 뒤 다시 시도해 주세요",
    "image.totalTooLarge": "이미지 합계 크기가 {size} 한도를 넘습니다. 일부를 빼고 다시 시도해 주세요",
    "image.unsupportedType": "PNG, JPG, WebP, GIF 이미지만 지원합니다",
    "input.commands": "파일 추가 또는 명령 실행",
    "input.file": "파일",
    "input.send": "메시지 보내기",
    "input.send.queue": "대기열에 추가",
    "input.send.steer": "즉시 전달",
    "input.stop": "생성 중지",
    "placeholder.default": "메시지를 입력하거나 작업을 실행하세요. / 명령, @ 파일 또는 세션",
    "placeholder.hero": "만들고 싶은 것을 설명해 주세요. / 명령, @ 파일 또는 세션",
    "placeholder.parentOffline": "상위 세션이 오프라인이라 보낼 수 없습니다. 실행 중지는 할 수 있습니다",
    "placeholder.plan": "작업을 설명하면 계획을 세웁니다",
    "placeholder.steerQueue": "Cmd/Ctrl+Enter를 누르면 대기 중인 메시지를 모두 즉시 전달합니다",
    "placeholder.unavailable": "세션을 쓸 수 없음",
    "placeholder.workspace": "시작하려면 워크스페이스를 고르세요",
    "queue.cancelEdit": "편집 취소",
    "queue.count": "대기 중인 메시지 {n}개",
    "queue.edit": "대기 중인 메시지 편집",
    "queue.edit.unsupported": "텍스트가 아닌 내용이 있어 아직 편집할 수 없습니다",
    "queue.editFailed": "편집하지 못했습니다. 메시지를 이미 보내기 시작했을 수 있습니다.",
    "queue.file": "대기 중인 파일 {name}",
    "queue.image": "대기 중인 메시지 이미지",
    "queue.remove": "대기 중인 메시지 제거",
    "queue.removeFailed": "제거하지 못했습니다. 메시지를 이미 보내기 시작했을 수 있습니다.",
    "queue.save": "대기 중인 메시지 저장",
    "queue.sending": "보내는 중…",
    "queue.steer": "대기 중인 메시지 즉시 전달",
    "queue.steer.unavailable": "즉시 전달은 에이전트가 실행 중일 때만 쓸 수 있습니다",
    "queue.steerFailed": "즉시 전달하지 못했습니다. 다시 시도해 주세요.",
    "read.collapseAria": "내용 접기",
    "read.expandAria": "{count}줄 더 펼치기",
    "read.expandRest": "… {count}줄 더 있음",
    "read.window": "전체 {total}줄 중 {shown}줄 표시",
    "row.failed": "실패",
    "row.input": "입력",
    "row.inspect": "검사",
    "row.output": "출력",
    "row.preparing": "도구 호출 준비 중",
    "row.running": "실행 중",
    "row.stopped": "중지됨",
    "search.collapseAria": "결과 접기",
    "search.expandAria": "결과 {count}줄 더 펼치기",
    "search.expandRest": "… {count}줄 더 있음",
    "search.matches": "일치 {shown}개 · 파일 {files}개",
    "search.matches.truncated": "일치 {total}개 중 {shown}개 표시 · 파일 {files}개",
    "search.noResults": "결과 없음",
    "search.paths": "경로 {shown}개",
    "search.paths.truncated": "경로 {total}개 중 {shown}개 표시",
    "session.hierarchy": "세션 계층",
    "settings.enter.description": "에이전트가 실행 중일 때 Enter 키와 보내기 버튼이 하는 동작입니다. Cmd/Ctrl+Enter는 다른 쪽 동작을 합니다",
    "settings.enter.queue": "대기열",
    "settings.enter.steer": "즉시 전달",
    "settings.enter.title": "실행 중 보내기 동작",
    "shortcut.complementary": "대기열 / 즉시 전달 중 다른 쪽 동작 사용",
    "shortcut.mention": "참조 메뉴 열기",
    "shortcut.newline": "줄 바꿈",
    "shortcut.slash": "명령 메뉴 열기",
    "terminal.collapseAria": "출력 접기",
    "terminal.done": "완료",
    "terminal.exitCode": "종료 코드 {code}",
    "terminal.expandAria": "남은 출력 {n}줄 펼치기",
    "terminal.expandRest": "… {n}줄 더 있음",
    "terminal.failed": "실패",
    "terminal.noExitCode": "종료 코드 없음",
    "terminal.noOutput": "출력 없음",
    "terminal.running": "실행 중",
    "terminal.sendInput": "(입력 보냄)",
    "terminal.session": "터미널 {sessionId}",
    "terminal.signal": "시그널 {signal}",
    "todo.completed": "{done}/{total} 완료",
    "todo.diff.added": "{count}개 추가",
    "todo.diff.addedItem": "추가됨",
    "todo.diff.compare": "이전 목록과 달라진 점",
    "todo.diff.initial": "첫 목록",
    "todo.diff.movedItem": "순서 바뀜",
    "todo.diff.noChanges": "목록이 바뀌지 않았습니다",
    "todo.diff.removed": "{count}개 제거",
    "todo.diff.removedItem": "제거됨",
    "todo.diff.unavailable": "이전 목록을 볼 수 없음",
    "todo.diff.unchanged": "{count}개 그대로",
    "todo.diff.updated": "{count}개 업데이트",
    "todo.diff.updatedItem": "상태 바뀜",
    "todo.progress.active": "{active}개 진행 중",
    "todo.progress.done": "{done}개 완료",
    "todo.progress.pending": "{pending}개 대기 중",
    "todo.rowTitle": "할 일 목록 업데이트",
    "todo.status.completed": "완료",
    "todo.status.inProgress": "진행 중",
    "todo.status.pending": "대기 중",
    "todo.title": "할 일",
    "tool.autoReviewNotExecuted": "도구를 실행하지 않았습니다. 이유: {reason}",
    "tool.autoReviewReasonFallback": "자동 검토에서 이 작업을 허용하지 않았습니다",
    "tool.autoReviewRejected": "자동 검토에서 거부됨",
    "tool.preparing.content": "내용 준비 중 {kilobytes}KB",
    "tool.title.bash": "Bash",
    "tool.title.closeTerminal": "터미널 닫기",
    "tool.title.code": "코드",
    "tool.title.createGoal": "목표 만들기",
    "tool.title.createSchedule": "알림 만들기",
    "tool.title.createTeamTask": "팀 작업 만들기",
    "tool.title.deleteSchedule": "알림 삭제",
    "tool.title.edit": "편집",
    "tool.title.findDefinition": "정의 찾기",
    "tool.title.findImplementation": "구현 찾기",
    "tool.title.findReferences": "참조 찾기",
    "tool.title.generic": "도구 호출",
    "tool.title.getGoal": "목표 보기",
    "tool.title.getTeamTask": "팀 작업 읽기",
    "tool.title.glob": "Glob",
    "tool.title.grep": "Grep",
    "tool.title.hoverSymbol": "심볼 검사",
    "tool.title.inspect": "Cordis 환경 조회",
    "tool.title.inspectPlugins": "플러그인 검사",
    "tool.title.inspectProviders": "공급자 검사",
    "tool.title.interruptAgent": "에이전트 중단",
    "tool.title.killJob": "백그라운드 작업 취소",
    "tool.title.listAgents": "서브에이전트 목록",
    "tool.title.listJobs": "백그라운드 작업 목록",
    "tool.title.listModels": "모델 목록",
    "tool.title.listSchedules": "알림 목록",
    "tool.title.listTeamTasks": "팀 작업 목록",
    "tool.title.listTerminals": "터미널 목록",
    "tool.title.lsp": "코드 심볼 조회",
    "tool.title.openTerminal": "터미널 열기",
    "tool.title.pwsh": "Pwsh",
    "tool.title.queryRuntime": "런타임 조회",
    "tool.title.ralph": "ralph 루프 실행",
    "tool.title.read": "읽기",
    "tool.title.readEvent": "이벤트 읽기",
    "tool.title.readImage": "이미지 읽기",
    "tool.title.readJob": "작업 출력 읽기",
    "tool.title.readTerminal": "터미널 읽기",
    "tool.title.removeCordis": "Cordis 플러그인 제거",
    "tool.title.runCordis": "Cordis 플러그인 실행",
    "tool.title.search": "검색",
    "tool.title.searchEvents": "이벤트 검색",
    "tool.title.searchSessions": "세션 검색",
    "tool.title.sendMessage": "메시지 보내기",
    "tool.title.signalTerminal": "터미널에 시그널 보내기",
    "tool.title.spawnTeammate": "팀원 만들기",
    "tool.title.stopCordis": "Cordis 플러그인 중지",
    "tool.title.subagent": "서브에이전트 만들기",
    "tool.title.traceEvent": "이벤트 추적",
    "tool.title.traceSession": "세션 추적",
    "tool.title.updateGoal": "목표 업데이트",
    "tool.title.updateSchedule": "알림 업데이트",
    "tool.title.updateTeamTask": "팀 작업 업데이트",
    "tool.title.waitAgent": "서브에이전트 기다리기",
    "tool.title.webFetch": "가져오기",
    "tool.title.webSearch": "검색",
    "tool.title.workflow": "워크플로 실행",
    "tool.title.write": "쓰기",
    "web.contentTruncated": "내용 잘림",
    "web.http": "HTTP",
    "web.noResults": "결과를 찾지 못했습니다",
    "web.sourcesTruncated": "출처 목록 잘림"
  },
  "feedback": {
    "action.dislike": "별로인 응답",
    "action.dislikeActive": "평가 취소",
    "action.like": "좋은 응답",
    "action.likeActive": "평가 취소",
    "category.instruction-following": "지시 이해와 수행",
    "category.other": "기타",
    "category.product-interaction": "제품 기능과 사용성",
    "category.resource-cost": "리소스 사용량과 비용",
    "category.security-privacy-permission": "보안, 개인정보, 권한",
    "category.service-stability": "안정성과 속도",
    "category.task-result": "작업 결과",
    "dialog.categories": "피드백 분류",
    "dialog.detail": "피드백 내용",
    "dialog.hint": "개선에 도움이 되도록 자세히 적어 주세요. 제출하면 현재 대화 로그도 함께 보냅니다.",
    "dialog.title": "피드백 보내기",
    "error.conflict": "다른 곳에서 피드백이 바뀌어 최신 상태를 표시합니다",
    "error.generic": "피드백을 저장하지 못했습니다",
    "error.load": "피드백을 불러오지 못했습니다",
    "error.noteTooLarge": "설명이 너무 깁니다. 줄인 뒤 다시 제출해 주세요",
    "toast.recorded": "피드백을 보내 주셔서 감사합니다"
  },
  "question": {
    "action.next": "다음",
    "action.skip": "건너뛰기",
    "custom.placeholder": "답변 입력",
    "error.incomplete": "이 질문에 먼저 답해 주세요.",
    "error.resubmit": "작업이 계속되기 전에 답변이 도착하지 않았습니다. 다시 제출해 주세요.",
    "error.unanswered": "옵션을 고르거나 직접 답을 입력해 주세요.",
    "error.unavailable": "지금은 제출할 수 없습니다. 잠시 뒤 다시 시도해 주세요.",
    "nav.cancel": "모든 질문 닫기",
    "nav.close": "패널 닫기(도구 호출에서 다시 열 수 있음)",
    "nav.maximize": "질문 카드 펼치기",
    "nav.minimize": "질문 카드 접기",
    "nav.next": "다음 질문",
    "nav.prev": "이전 질문",
    "option.recommended": "추천",
    "plan.approve": "승인",
    "plan.decline": "거절",
    "plan.discuss": "수정 요청",
    "plan.header": "계획 검토",
    "reply.answerLabel": "답변: ",
    "reply.close": "질문 세부 정보 닫기",
    "reply.label": "앞선 대기 중인 질문에 답하기",
    "reply.open": "질문 세부 정보 열기",
    "reply.skipped": "건너뜀",
    "review.skipped": "이 질문은 건너뛰었습니다.",
    "review.status": "답변함",
    "status.sent": "답변을 보냈지만 패널을 닫지 못했습니다.",
    "wait.continued": "작업은 계속됨, 아직 답할 수 있음",
    "wait.countdown": "{seconds}초 뒤 계속",
    "wait.held": "답변을 기다리는 중",
    "wait.paused": "일시 중지됨 · {seconds}초 남음",
    "wait.takeTime": "천천히 답하기"
  },
  "reference": {
    "candidate.noCwd": "(작업 디렉터리 없음)",
    "crumb.root": "워크스페이스",
    "section.files": "파일 및 폴더",
    "section.sessions": "세션",
    "section.subagents": "서브에이전트",
    "time.days": "{n}일",
    "time.hours": "{n}시간",
    "time.minutes": "{n}분",
    "time.months": "{n}개월",
    "time.now": "방금",
    "time.years": "{n}년"
  },
  "skill": {
    "menu.userOnly": "사용자 전용",
    "row.failed": "스킬 불러오기 실패",
    "row.inspect": "검사",
    "row.instructions": "지침",
    "row.preparing": "스킬 불러오기 준비 중",
    "row.running": "스킬 불러오는 중",
    "row.stopped": "스킬 불러오기 중지됨",
    "row.title": "스킬"
  },
  "slash.menu": {
    "command": "명령",
    "crumbs.aria": "폴더 탐색",
    "drill.aria": "폴더 보기",
    "drill.hint": "폴더 보기",
    "drill.key": "Tab",
    "loading": "불러오는 중…",
    "skill": "스킬",
    "subagent": "서브에이전트",
    "suggestions.aria": "추천 항목"
  },
  "trajectory": {
    "attachment.imageName": "이미지 {index}",
    "attachment.list": "첨부 파일",
    "block.label": "블록 #{index} {type}",
    "block.openSummary": "블록 #{index} 도구 호출 요약 열기",
    "block.openSummaryTitle": "도구 호출 요약 열기",
    "code.copyOutput": "출력 복사",
    "code.copySource": "코드 복사",
    "code.originalJson": "원본 JSON",
    "code.output": "출력",
    "code.running": "실행 중…",
    "code.source": "코드",
    "column.input": "입력",
    "column.model": "모델",
    "column.output": "출력",
    "column.think": "생각",
    "column.time": "시간",
    "column.tools": "도구",
    "details.assistantMessage": "어시스턴트 메시지",
    "details.close": "세부 정보 닫기",
    "details.compacted": "압축됨",
    "details.error": "오류",
    "details.event": "이벤트 세부 정보",
    "details.failure.auth": "API 키가 올바르지 않습니다",
    "details.hierarchy": "계층",
    "details.model": "모델",
    "details.provider": "공급자",
    "details.purpose": "용도",
    "details.resize": "이벤트 세부 정보 크기 조절",
    "details.resizeTitle": "끌어서 크기를 조절합니다. 두 번 클릭하면 원래대로 돌아갑니다.",
    "details.result": "결과",
    "details.retry": "재시도",
    "details.retryDelay": "재시도 대기 시간",
    "details.scheduled": "예약됨",
    "details.source": "출처",
    "details.status": "상태",
    "details.subtoolCalls": "하위 도구 호출",
    "details.toolCall": "도구 호출",
    "details.toolCalls": "도구 호출",
    "group.compaction": "압축 {seq}",
    "group.message": "메시지",
    "group.step": "단계 {step}",
    "history.clickToLoadEarlier": "클릭해 이전 기록 불러오기",
    "history.loadEarlier": "이전 기록 불러오기",
    "history.loadingEarlier": "이전 기록 불러오는 중…",
    "history.loadingEarlierAria": "이전 기록 불러오는 중…",
    "history.loadingTrajectory": "실행 기록 불러오는 중…",
    "kind.assistant": "어시스턴트",
    "kind.compacted": "압축됨",
    "kind.context": "컨텍스트",
    "kind.message": "메시지",
    "kind.sub": "하위",
    "kind.subtool": "하위 도구",
    "kind.system": "시스템",
    "kind.tool": "도구",
    "kind.user": "사용자",
    "layout.compacted": "컨텍스트 압축됨",
    "layout.compacting": "컨텍스트 압축 중…",
    "layout.compactionFailed": "압축 실패",
    "layout.compactionInterrupted": "압축이 끝나기 전에 중단되었습니다.",
    "layout.fileAttachments": "파일 ×{count}",
    "layout.imageCount": "이미지 ×{count}",
    "layout.initialSystemPrompt": "초기 시스템 프롬프트",
    "layout.systemPromptAndToolsUpdated": "시스템 프롬프트와 도구 업데이트됨",
    "layout.systemPromptUpdated": "시스템 프롬프트 업데이트됨",
    "layout.toolAdded": "도구 추가됨: {name}",
    "layout.toolCallOnly": "도구 호출만",
    "layout.toolRemoved": "도구 제거됨: {name}",
    "layout.toolUpdateNotice": "도구 업데이트됨",
    "layout.toolsAdded": "추가됨: {names}",
    "layout.toolsAddedCount": "{count}개 추가됨",
    "layout.toolsChanged": "{added}개 추가, {removed}개 제거",
    "layout.toolsRemoved": "제거됨: {names}",
    "layout.toolsRemovedCount": "{count}개 제거됨",
    "layout.toolsUpdated": "도구 업데이트됨",
    "options.json": "요청 옵션 JSON",
    "options.notRecorded": "옵션이 기록되지 않음",
    "record.json": "JSON",
    "record.namedParametersJson": "{name} 매개변수 JSON",
    "record.noContent": "내용 없음",
    "record.noOutput": "출력 없음",
    "record.noPayload": "기록된 페이로드 없음",
    "record.noResult": "기록된 결과 없음",
    "record.outputJson": "결과 JSON",
    "record.parameters": "매개변수",
    "record.parametersJson": "매개변수 JSON",
    "record.payloadJson": "페이로드 JSON",
    "record.resultJson": "결과 JSON",
    "record.schemaUnavailable": "스키마 없음",
    "record.systemPrompt": "시스템 프롬프트",
    "record.systemPromptMissing": "이 요청에는 시스템 프롬프트가 없습니다",
    "record.thinking": "생각",
    "record.toolCallOnly": "(도구 호출만)",
    "record.tools": "도구",
    "record.toolsMissing": "이 요청에는 도구가 없습니다",
    "record.wrapLines": "줄 바꿈",
    "request.collapsedAssistant": "어시스턴트",
    "request.collapsedSummary": "접힌 {kind} 요약, {summary}",
    "request.collapsedTurn": "턴",
    "request.compaction": "압축 · {section}",
    "request.compactionPurpose": "압축",
    "request.label": "요청 #{request}",
    "request.labelCompaction": "요청 #{request} · 압축",
    "request.noContent": "내용 없음",
    "request.retryProgress": "{retry}/{maximum}",
    "request.rowAria": "{request}{kind}, {content}",
    "request.rowAriaCompaction": "요청 {request}, 압축",
    "request.rowPrefix": "요청 {request}, ",
    "section.betweenTurns": "턴 사이",
    "source.goal": "목표",
    "source.goalRound": "목표 · {round}회차",
    "source.messageJson": "메시지 원본 JSON",
    "source.notRecorded": "출처가 기록되지 않음",
    "source.plugin": "플러그인",
    "source.pluginNamed": "플러그인 · {plugin}",
    "source.unknown": "알 수 없음",
    "source.user": "사용자",
    "status.completed": "완료",
    "status.failed": "실패",
    "status.pending": "대기 중",
    "summary.steps.one": "단계 {count}개",
    "summary.steps.other": "단계 {count}개",
    "summary.toolCalls.one": "도구 호출 {count}회",
    "summary.toolCalls.other": "도구 호출 {count}회",
    "tab.diff": "변경 사항",
    "tab.options": "옵션",
    "tab.payload": "페이로드",
    "tab.preview": "미리보기",
    "tab.raw": "원본",
    "tab.rawOutput": "원본 출력",
    "tab.result": "결과",
    "tab.schema": "스키마",
    "tab.source": "출처",
    "tab.summary": "요약",
    "tab.systemPrompt": "시스템 프롬프트",
    "tab.timing": "시간",
    "tab.tools": "도구",
    "tab.usage": "사용량",
    "timeline.aria": "실행 기록 타임라인",
    "timeline.noTimingData": "시간 데이터 없음",
    "timeline.overviewAria": "타임라인 개요, 가로로 끌어서 이벤트 구간을 확대합니다",
    "timeline.started": "시작 {time}",
    "timeline.total": "합계 {duration}",
    "timeline.ttftDecoding": "TTFT {ttft} · 디코딩 {decoding}",
    "timing.duration": "소요 시간",
    "timing.durationTooShort": "소요 시간이 너무 짧음",
    "timing.firstTokenUnavailable": "첫 토큰 정보 없음",
    "timing.generation": "생성",
    "timing.notAvailable": "정보 없음",
    "timing.notRecorded": "기록되지 않음",
    "timing.outputTokensUnavailable": "출력 토큰 정보 없음",
    "timing.request": "요청 시간",
    "timing.sessionTimestamps": "세션 타임스탬프",
    "timing.sessionTimestampsRunning": "세션 타임스탬프(실행 중)",
    "timing.showLocalTime": "현지 시각 표시",
    "timing.showUnixTimestamp": "Unix 타임스탬프 표시",
    "timing.source": "시간 출처",
    "timing.started": "시작",
    "timing.stepStartUnavailable": "단계 시작 정보 없음",
    "timing.throughput": "처리량",
    "timing.totalDuration": "전체 소요 시간",
    "timing.ttft": "TTFT",
    "timing.usageUnavailable": "사용량 정보 없음",
    "toolbar.actualTime": "실제 시간",
    "toolbar.aria": "실행 기록 도구 모음",
    "toolbar.calls": "호출",
    "toolbar.collapseCalls": "호출 접기",
    "toolbar.collapseTurns": "턴 접기",
    "toolbar.duration": "소요 시간",
    "toolbar.expandCalls": "호출 펼치기",
    "toolbar.expandTurns": "턴 펼치기",
    "toolbar.search": "실행 기록 검색",
    "toolbar.searchPlaceholder": "검색",
    "toolbar.turns": "턴",
    "toolbar.useActualDuration": "실제 소요 시간으로 표시",
    "toolbar.useEqualWidth": "작업을 같은 너비로 표시",
    "turn.label": "턴 {turn}",
    "unit.milliseconds": "{value} ms",
    "unit.seconds": "{value}초",
    "unit.tokens": "{value} tok",
    "unit.tokensPerSecond": "{value} tok/s",
    "usage.cacheCreated": "캐시 생성",
    "usage.cached": "캐시됨",
    "usage.content": "콘텐츠",
    "usage.input": "입력",
    "usage.notReported": "사용량이 보고되지 않음",
    "usage.other": "기타",
    "usage.output": "출력",
    "usage.reasoning": "추론",
    "usage.sessionCumulative": "세션 누적",
    "usage.thisRequest": "이번 요청",
    "usage.tokens": "토큰",
    "view.trajectory": "실행 기록"
  }
}

window.__ModuleLoader__.load({
  id: 'dsh-locale-ko',
  factory: () => ({
    inject: ['locale'],
    apply(ctx) {
      ctx.effect(() => ctx.locale.addLanguage({ id: 'ko', label: '한국어', fallback: 'en' }), 'dsh-locale-ko: language')
      for (const [ns, dict] of Object.entries(dictionaries)) {
        ctx.effect(() => ctx.locale.register(ns, 'ko', dict), `dsh-locale-ko: ${ns}`)
      }
    },
  }),
})
